apiVersion: logpush.upjet-cloudflare.m.upbound.io/v1alpha1
kind: Job
metadata:
  annotations:
    meta.upbound.io/example-id: logpush/v1alpha1/job
  labels:
    testing.upbound.io/example-name: example_logpush_job
  name: example-logpush-job
  namespace: crossplane-system
spec:
  forProvider:
    dataset: http_requests
    destinationConfSecretRef:
      key: example-key
      name: example-secret
    enabled: false
    filter: '{"where":{"and":[{"key":"ClientRequestPath","operator":"contains","value":"/static"},{"key":"ClientRequestHost","operator":"eq","value":"example.com"}]}}'
    filterAttackTraffic: true
    frequency: high
    kind: ""
    logpullOptions: fields=RayID,ClientIP,EdgeStartTimestamp&timestamps=rfc3339
    maxUploadBytes: 5000000
    maxUploadIntervalSeconds: 30
    maxUploadRecords: 1000
    name: example.com
    outputOptions:
      batchPrefix: batch_prefix
      batchSuffix: batch_suffix
      cve202144228: true
      fieldDelimiter: field_delimiter
      fieldNames:
      - ClientIP
      - EdgeStartTimestamp
      - RayID
      mergeSubrequests: true
      outputType: ndjson
      recordDelimiter: record_delimiter
      recordPrefix: record_prefix
      recordSuffix: record_suffix
      recordTemplate: record_template
      sampleRate: 1
      timestampFormat: unixnano
    ownershipChallengeSecretRef:
      key: example-key
      name: example-secret
    zoneId: zone_id
