//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedRequestHeadersInitParameters) DeepCopyInto(out *ManagedRequestHeadersInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedRequestHeadersInitParameters.
func (in *ManagedRequestHeadersInitParameters) DeepCopy() *ManagedRequestHeadersInitParameters {
	if in == nil {
		return nil
	}
	out := new(ManagedRequestHeadersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedRequestHeadersObservation) DeepCopyInto(out *ManagedRequestHeadersObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedRequestHeadersObservation.
func (in *ManagedRequestHeadersObservation) DeepCopy() *ManagedRequestHeadersObservation {
	if in == nil {
		return nil
	}
	out := new(ManagedRequestHeadersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedRequestHeadersParameters) DeepCopyInto(out *ManagedRequestHeadersParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedRequestHeadersParameters.
func (in *ManagedRequestHeadersParameters) DeepCopy() *ManagedRequestHeadersParameters {
	if in == nil {
		return nil
	}
	out := new(ManagedRequestHeadersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedResponseHeadersInitParameters) DeepCopyInto(out *ManagedResponseHeadersInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedResponseHeadersInitParameters.
func (in *ManagedResponseHeadersInitParameters) DeepCopy() *ManagedResponseHeadersInitParameters {
	if in == nil {
		return nil
	}
	out := new(ManagedResponseHeadersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedResponseHeadersObservation) DeepCopyInto(out *ManagedResponseHeadersObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedResponseHeadersObservation.
func (in *ManagedResponseHeadersObservation) DeepCopy() *ManagedResponseHeadersObservation {
	if in == nil {
		return nil
	}
	out := new(ManagedResponseHeadersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedResponseHeadersParameters) DeepCopyInto(out *ManagedResponseHeadersParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedResponseHeadersParameters.
func (in *ManagedResponseHeadersParameters) DeepCopy() *ManagedResponseHeadersParameters {
	if in == nil {
		return nil
	}
	out := new(ManagedResponseHeadersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transforms) DeepCopyInto(out *Transforms) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transforms.
func (in *Transforms) DeepCopy() *Transforms {
	if in == nil {
		return nil
	}
	out := new(Transforms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Transforms) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformsInitParameters) DeepCopyInto(out *TransformsInitParameters) {
	*out = *in
	if in.ManagedRequestHeaders != nil {
		in, out := &in.ManagedRequestHeaders, &out.ManagedRequestHeaders
		*out = make([]ManagedRequestHeadersInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedResponseHeaders != nil {
		in, out := &in.ManagedResponseHeaders, &out.ManagedResponseHeaders
		*out = make([]ManagedResponseHeadersInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformsInitParameters.
func (in *TransformsInitParameters) DeepCopy() *TransformsInitParameters {
	if in == nil {
		return nil
	}
	out := new(TransformsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformsList) DeepCopyInto(out *TransformsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Transforms, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformsList.
func (in *TransformsList) DeepCopy() *TransformsList {
	if in == nil {
		return nil
	}
	out := new(TransformsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransformsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformsObservation) DeepCopyInto(out *TransformsObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ManagedRequestHeaders != nil {
		in, out := &in.ManagedRequestHeaders, &out.ManagedRequestHeaders
		*out = make([]ManagedRequestHeadersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedResponseHeaders != nil {
		in, out := &in.ManagedResponseHeaders, &out.ManagedResponseHeaders
		*out = make([]ManagedResponseHeadersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformsObservation.
func (in *TransformsObservation) DeepCopy() *TransformsObservation {
	if in == nil {
		return nil
	}
	out := new(TransformsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformsParameters) DeepCopyInto(out *TransformsParameters) {
	*out = *in
	if in.ManagedRequestHeaders != nil {
		in, out := &in.ManagedRequestHeaders, &out.ManagedRequestHeaders
		*out = make([]ManagedRequestHeadersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedResponseHeaders != nil {
		in, out := &in.ManagedResponseHeaders, &out.ManagedResponseHeaders
		*out = make([]ManagedResponseHeadersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ZoneID != nil {
		in, out := &in.ZoneID, &out.ZoneID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformsParameters.
func (in *TransformsParameters) DeepCopy() *TransformsParameters {
	if in == nil {
		return nil
	}
	out := new(TransformsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformsSpec) DeepCopyInto(out *TransformsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformsSpec.
func (in *TransformsSpec) DeepCopy() *TransformsSpec {
	if in == nil {
		return nil
	}
	out := new(TransformsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformsStatus) DeepCopyInto(out *TransformsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformsStatus.
func (in *TransformsStatus) DeepCopy() *TransformsStatus {
	if in == nil {
		return nil
	}
	out := new(TransformsStatus)
	in.DeepCopyInto(out)
	return out
}
