apiVersion: secretsstore.upjet-cloudflare.upbound.io/v1alpha1
kind: StoreSecret
metadata:
  annotations:
    meta.upbound.io/example-id: secretsstore/v1alpha1/storesecret
  labels:
    testing.upbound.io/example-name: example_secrets_store_secret
  name: example-secrets-store-secret
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    storeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
