// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DNSInitParameters struct {

	// (Boolean) Specify whether to log all requests to this service.
	// Specify whether to log all requests to this service.
	LogAll *bool `json:"logAll,omitempty" tf:"log_all,omitempty"`

	// (Boolean) Specify whether to log only blocking requests to this service.
	// Specify whether to log only blocking requests to this service.
	LogBlocks *bool `json:"logBlocks,omitempty" tf:"log_blocks,omitempty"`
}

type DNSObservation struct {

	// (Boolean) Specify whether to log all requests to this service.
	// Specify whether to log all requests to this service.
	LogAll *bool `json:"logAll,omitempty" tf:"log_all,omitempty"`

	// (Boolean) Specify whether to log only blocking requests to this service.
	// Specify whether to log only blocking requests to this service.
	LogBlocks *bool `json:"logBlocks,omitempty" tf:"log_blocks,omitempty"`
}

type DNSParameters struct {

	// (Boolean) Specify whether to log all requests to this service.
	// Specify whether to log all requests to this service.
	// +kubebuilder:validation:Optional
	LogAll *bool `json:"logAll,omitempty" tf:"log_all,omitempty"`

	// (Boolean) Specify whether to log only blocking requests to this service.
	// Specify whether to log only blocking requests to this service.
	// +kubebuilder:validation:Optional
	LogBlocks *bool `json:"logBlocks,omitempty" tf:"log_blocks,omitempty"`
}

type HTTPInitParameters struct {

	// (Boolean) Specify whether to log all requests to this service.
	// Specify whether to log all requests to this service.
	LogAll *bool `json:"logAll,omitempty" tf:"log_all,omitempty"`

	// (Boolean) Specify whether to log only blocking requests to this service.
	// Specify whether to log only blocking requests to this service.
	LogBlocks *bool `json:"logBlocks,omitempty" tf:"log_blocks,omitempty"`
}

type HTTPObservation struct {

	// (Boolean) Specify whether to log all requests to this service.
	// Specify whether to log all requests to this service.
	LogAll *bool `json:"logAll,omitempty" tf:"log_all,omitempty"`

	// (Boolean) Specify whether to log only blocking requests to this service.
	// Specify whether to log only blocking requests to this service.
	LogBlocks *bool `json:"logBlocks,omitempty" tf:"log_blocks,omitempty"`
}

type HTTPParameters struct {

	// (Boolean) Specify whether to log all requests to this service.
	// Specify whether to log all requests to this service.
	// +kubebuilder:validation:Optional
	LogAll *bool `json:"logAll,omitempty" tf:"log_all,omitempty"`

	// (Boolean) Specify whether to log only blocking requests to this service.
	// Specify whether to log only blocking requests to this service.
	// +kubebuilder:validation:Optional
	LogBlocks *bool `json:"logBlocks,omitempty" tf:"log_blocks,omitempty"`
}

type L4InitParameters struct {

	// (Boolean) Specify whether to log all requests to this service.
	// Specify whether to log all requests to this service.
	LogAll *bool `json:"logAll,omitempty" tf:"log_all,omitempty"`

	// (Boolean) Specify whether to log only blocking requests to this service.
	// Specify whether to log only blocking requests to this service.
	LogBlocks *bool `json:"logBlocks,omitempty" tf:"log_blocks,omitempty"`
}

type L4Observation struct {

	// (Boolean) Specify whether to log all requests to this service.
	// Specify whether to log all requests to this service.
	LogAll *bool `json:"logAll,omitempty" tf:"log_all,omitempty"`

	// (Boolean) Specify whether to log only blocking requests to this service.
	// Specify whether to log only blocking requests to this service.
	LogBlocks *bool `json:"logBlocks,omitempty" tf:"log_blocks,omitempty"`
}

type L4Parameters struct {

	// (Boolean) Specify whether to log all requests to this service.
	// Specify whether to log all requests to this service.
	// +kubebuilder:validation:Optional
	LogAll *bool `json:"logAll,omitempty" tf:"log_all,omitempty"`

	// (Boolean) Specify whether to log only blocking requests to this service.
	// Specify whether to log only blocking requests to this service.
	// +kubebuilder:validation:Optional
	LogBlocks *bool `json:"logBlocks,omitempty" tf:"log_blocks,omitempty"`
}

type SettingsByRuleTypeInitParameters struct {

	// (Attributes) Configure logging settings for DNS firewall. (see below for nested schema)
	DNS *DNSInitParameters `json:"dns,omitempty" tf:"dns,omitempty"`

	// (Attributes) Configure logging settings for HTTP/HTTPS firewall. (see below for nested schema)
	HTTP *HTTPInitParameters `json:"http,omitempty" tf:"http,omitempty"`

	// (Attributes) Configure logging settings for Network firewall. (see below for nested schema)
	L4 *L4InitParameters `json:"l4,omitempty" tf:"l4,omitempty"`
}

type SettingsByRuleTypeObservation struct {

	// (Attributes) Configure logging settings for DNS firewall. (see below for nested schema)
	DNS *DNSObservation `json:"dns,omitempty" tf:"dns,omitempty"`

	// (Attributes) Configure logging settings for HTTP/HTTPS firewall. (see below for nested schema)
	HTTP *HTTPObservation `json:"http,omitempty" tf:"http,omitempty"`

	// (Attributes) Configure logging settings for Network firewall. (see below for nested schema)
	L4 *L4Observation `json:"l4,omitempty" tf:"l4,omitempty"`
}

type SettingsByRuleTypeParameters struct {

	// (Attributes) Configure logging settings for DNS firewall. (see below for nested schema)
	// +kubebuilder:validation:Optional
	DNS *DNSParameters `json:"dns,omitempty" tf:"dns,omitempty"`

	// (Attributes) Configure logging settings for HTTP/HTTPS firewall. (see below for nested schema)
	// +kubebuilder:validation:Optional
	HTTP *HTTPParameters `json:"http,omitempty" tf:"http,omitempty"`

	// (Attributes) Configure logging settings for Network firewall. (see below for nested schema)
	// +kubebuilder:validation:Optional
	L4 *L4Parameters `json:"l4,omitempty" tf:"l4,omitempty"`
}

type TrustGatewayLoggingInitParameters struct {

	// (String)
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (Boolean) Indicate whether to redact personally identifiable information from activity logging (PII fields include source IP, user email, user ID, device ID, URL, referrer, and user agent).
	// Indicate whether to redact personally identifiable information from activity logging (PII fields include source IP, user email, user ID, device ID, URL, referrer, and user agent).
	RedactPii *bool `json:"redactPii,omitempty" tf:"redact_pii,omitempty"`

	// (Attributes) Configure logging settings for each rule type. (see below for nested schema)
	SettingsByRuleType *SettingsByRuleTypeInitParameters `json:"settingsByRuleType,omitempty" tf:"settings_by_rule_type,omitempty"`
}

type TrustGatewayLoggingObservation struct {

	// (String)
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Indicate whether to redact personally identifiable information from activity logging (PII fields include source IP, user email, user ID, device ID, URL, referrer, and user agent).
	// Indicate whether to redact personally identifiable information from activity logging (PII fields include source IP, user email, user ID, device ID, URL, referrer, and user agent).
	RedactPii *bool `json:"redactPii,omitempty" tf:"redact_pii,omitempty"`

	// (Attributes) Configure logging settings for each rule type. (see below for nested schema)
	SettingsByRuleType *SettingsByRuleTypeObservation `json:"settingsByRuleType,omitempty" tf:"settings_by_rule_type,omitempty"`
}

type TrustGatewayLoggingParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (Boolean) Indicate whether to redact personally identifiable information from activity logging (PII fields include source IP, user email, user ID, device ID, URL, referrer, and user agent).
	// Indicate whether to redact personally identifiable information from activity logging (PII fields include source IP, user email, user ID, device ID, URL, referrer, and user agent).
	// +kubebuilder:validation:Optional
	RedactPii *bool `json:"redactPii,omitempty" tf:"redact_pii,omitempty"`

	// (Attributes) Configure logging settings for each rule type. (see below for nested schema)
	// +kubebuilder:validation:Optional
	SettingsByRuleType *SettingsByRuleTypeParameters `json:"settingsByRuleType,omitempty" tf:"settings_by_rule_type,omitempty"`
}

// TrustGatewayLoggingSpec defines the desired state of TrustGatewayLogging
type TrustGatewayLoggingSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TrustGatewayLoggingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TrustGatewayLoggingInitParameters `json:"initProvider,omitempty"`
}

// TrustGatewayLoggingStatus defines the observed state of TrustGatewayLogging.
type TrustGatewayLoggingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TrustGatewayLoggingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TrustGatewayLogging is the Schema for the TrustGatewayLoggings API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,upjet-cloudflare}
type TrustGatewayLogging struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountId) || (has(self.initProvider) && has(self.initProvider.accountId))",message="spec.forProvider.accountId is a required parameter"
	Spec   TrustGatewayLoggingSpec   `json:"spec"`
	Status TrustGatewayLoggingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TrustGatewayLoggingList contains a list of TrustGatewayLoggings
type TrustGatewayLoggingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TrustGatewayLogging `json:"items"`
}

// Repository type metadata.
var (
	TrustGatewayLogging_Kind             = "TrustGatewayLogging"
	TrustGatewayLogging_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TrustGatewayLogging_Kind}.String()
	TrustGatewayLogging_KindAPIVersion   = TrustGatewayLogging_Kind + "." + CRDGroupVersion.String()
	TrustGatewayLogging_GroupVersionKind = CRDGroupVersion.WithKind(TrustGatewayLogging_Kind)
)

func init() {
	SchemeBuilder.Register(&TrustGatewayLogging{}, &TrustGatewayLoggingList{})
}
