// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AuditSSHInitParameters struct {

	// (Boolean) Enable SSH command logging.
	// Enable SSH command logging.
	CommandLogging *bool `json:"commandLogging,omitempty" tf:"command_logging,omitempty"`
}

type AuditSSHObservation struct {

	// (Boolean) Enable SSH command logging.
	// Enable SSH command logging.
	CommandLogging *bool `json:"commandLogging,omitempty" tf:"command_logging,omitempty"`
}

type AuditSSHParameters struct {

	// (Boolean) Enable SSH command logging.
	// Enable SSH command logging.
	// +kubebuilder:validation:Optional
	CommandLogging *bool `json:"commandLogging,omitempty" tf:"command_logging,omitempty"`
}

type BisoAdminControlsInitParameters struct {

	// (String) Configure copy behavior. If set to remote_only, users cannot copy isolated content from the remote browser to the local clipboard. If this field is absent, copying remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	// Configure copy behavior. If set to remote_only, users cannot copy isolated content from the remote browser to the local clipboard. If this field is absent, copying remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	Copy *string `json:"copy,omitempty" tf:"copy,omitempty"`

	// pasting. Only applies when version == "v1".
	// Set to false to enable copy-pasting. Only applies when `version == "v1"`.
	Dcp *bool `json:"dcp,omitempty" tf:"dcp,omitempty"`

	// (Boolean) Set to false to enable downloading. Only applies when version == "v1".
	// Set to false to enable downloading. Only applies when `version == "v1"`.
	Dd *bool `json:"dd,omitempty" tf:"dd,omitempty"`

	// (Boolean) Set to false to enable keyboard usage. Only applies when version == "v1".
	// Set to false to enable keyboard usage. Only applies when `version == "v1"`.
	Dk *bool `json:"dk,omitempty" tf:"dk,omitempty"`

	// (String) Configure download behavior. When set to remote_only, users can view downloads but cannot save them. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	// Configure download behavior. When set to remote_only, users can view downloads but cannot save them. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	Download *string `json:"download,omitempty" tf:"download,omitempty"`

	// (Boolean) Set to false to enable printing. Only applies when version == "v1".
	// Set to false to enable printing. Only applies when `version == "v1"`.
	Dp *bool `json:"dp,omitempty" tf:"dp,omitempty"`

	// (Boolean) Set to false to enable uploading. Only applies when version == "v1".
	// Set to false to enable uploading. Only applies when `version == "v1"`.
	Du *bool `json:"du,omitempty" tf:"du,omitempty"`

	// (String) Configure keyboard usage behavior. If this field is absent, keyboard usage remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	// Configure keyboard usage behavior. If this field is absent, keyboard usage remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	Keyboard *string `json:"keyboard,omitempty" tf:"keyboard,omitempty"`

	// (String) Configure paste behavior. If set to remote_only, users cannot paste content from the local clipboard into isolated pages. If this field is absent, pasting remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	// Configure paste behavior. If set to remote_only, users cannot paste content from the local clipboard into isolated pages. If this field is absent, pasting remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	Paste *string `json:"paste,omitempty" tf:"paste,omitempty"`

	// (String) Configure print behavior. Default, Printing is enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	// Configure print behavior. Default, Printing is enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	Printing *string `json:"printing,omitempty" tf:"printing,omitempty"`

	// (String) Configure upload behavior. If this field is absent, uploading remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	// Configure upload behavior. If this field is absent, uploading remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	Upload *string `json:"upload,omitempty" tf:"upload,omitempty"`

	// only).
	// Indicate which version of the browser isolation controls should apply.
	// Available values: "v1", "v2".
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type BisoAdminControlsObservation struct {

	// (String) Configure copy behavior. If set to remote_only, users cannot copy isolated content from the remote browser to the local clipboard. If this field is absent, copying remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	// Configure copy behavior. If set to remote_only, users cannot copy isolated content from the remote browser to the local clipboard. If this field is absent, copying remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	Copy *string `json:"copy,omitempty" tf:"copy,omitempty"`

	// pasting. Only applies when version == "v1".
	// Set to false to enable copy-pasting. Only applies when `version == "v1"`.
	Dcp *bool `json:"dcp,omitempty" tf:"dcp,omitempty"`

	// (Boolean) Set to false to enable downloading. Only applies when version == "v1".
	// Set to false to enable downloading. Only applies when `version == "v1"`.
	Dd *bool `json:"dd,omitempty" tf:"dd,omitempty"`

	// (Boolean) Set to false to enable keyboard usage. Only applies when version == "v1".
	// Set to false to enable keyboard usage. Only applies when `version == "v1"`.
	Dk *bool `json:"dk,omitempty" tf:"dk,omitempty"`

	// (String) Configure download behavior. When set to remote_only, users can view downloads but cannot save them. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	// Configure download behavior. When set to remote_only, users can view downloads but cannot save them. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	Download *string `json:"download,omitempty" tf:"download,omitempty"`

	// (Boolean) Set to false to enable printing. Only applies when version == "v1".
	// Set to false to enable printing. Only applies when `version == "v1"`.
	Dp *bool `json:"dp,omitempty" tf:"dp,omitempty"`

	// (Boolean) Set to false to enable uploading. Only applies when version == "v1".
	// Set to false to enable uploading. Only applies when `version == "v1"`.
	Du *bool `json:"du,omitempty" tf:"du,omitempty"`

	// (String) Configure keyboard usage behavior. If this field is absent, keyboard usage remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	// Configure keyboard usage behavior. If this field is absent, keyboard usage remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	Keyboard *string `json:"keyboard,omitempty" tf:"keyboard,omitempty"`

	// (String) Configure paste behavior. If set to remote_only, users cannot paste content from the local clipboard into isolated pages. If this field is absent, pasting remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	// Configure paste behavior. If set to remote_only, users cannot paste content from the local clipboard into isolated pages. If this field is absent, pasting remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	Paste *string `json:"paste,omitempty" tf:"paste,omitempty"`

	// (String) Configure print behavior. Default, Printing is enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	// Configure print behavior. Default, Printing is enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	Printing *string `json:"printing,omitempty" tf:"printing,omitempty"`

	// (String) Configure upload behavior. If this field is absent, uploading remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	// Configure upload behavior. If this field is absent, uploading remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	Upload *string `json:"upload,omitempty" tf:"upload,omitempty"`

	// only).
	// Indicate which version of the browser isolation controls should apply.
	// Available values: "v1", "v2".
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type BisoAdminControlsParameters struct {

	// (String) Configure copy behavior. If set to remote_only, users cannot copy isolated content from the remote browser to the local clipboard. If this field is absent, copying remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	// Configure copy behavior. If set to remote_only, users cannot copy isolated content from the remote browser to the local clipboard. If this field is absent, copying remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	// +kubebuilder:validation:Optional
	Copy *string `json:"copy,omitempty" tf:"copy,omitempty"`

	// pasting. Only applies when version == "v1".
	// Set to false to enable copy-pasting. Only applies when `version == "v1"`.
	// +kubebuilder:validation:Optional
	Dcp *bool `json:"dcp,omitempty" tf:"dcp,omitempty"`

	// (Boolean) Set to false to enable downloading. Only applies when version == "v1".
	// Set to false to enable downloading. Only applies when `version == "v1"`.
	// +kubebuilder:validation:Optional
	Dd *bool `json:"dd,omitempty" tf:"dd,omitempty"`

	// (Boolean) Set to false to enable keyboard usage. Only applies when version == "v1".
	// Set to false to enable keyboard usage. Only applies when `version == "v1"`.
	// +kubebuilder:validation:Optional
	Dk *bool `json:"dk,omitempty" tf:"dk,omitempty"`

	// (String) Configure download behavior. When set to remote_only, users can view downloads but cannot save them. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	// Configure download behavior. When set to remote_only, users can view downloads but cannot save them. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	// +kubebuilder:validation:Optional
	Download *string `json:"download,omitempty" tf:"download,omitempty"`

	// (Boolean) Set to false to enable printing. Only applies when version == "v1".
	// Set to false to enable printing. Only applies when `version == "v1"`.
	// +kubebuilder:validation:Optional
	Dp *bool `json:"dp,omitempty" tf:"dp,omitempty"`

	// (Boolean) Set to false to enable uploading. Only applies when version == "v1".
	// Set to false to enable uploading. Only applies when `version == "v1"`.
	// +kubebuilder:validation:Optional
	Du *bool `json:"du,omitempty" tf:"du,omitempty"`

	// (String) Configure keyboard usage behavior. If this field is absent, keyboard usage remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	// Configure keyboard usage behavior. If this field is absent, keyboard usage remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	// +kubebuilder:validation:Optional
	Keyboard *string `json:"keyboard,omitempty" tf:"keyboard,omitempty"`

	// (String) Configure paste behavior. If set to remote_only, users cannot paste content from the local clipboard into isolated pages. If this field is absent, pasting remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	// Configure paste behavior. If set to remote_only, users cannot paste content from the local clipboard into isolated pages. If this field is absent, pasting remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled", "remote_only".
	// +kubebuilder:validation:Optional
	Paste *string `json:"paste,omitempty" tf:"paste,omitempty"`

	// (String) Configure print behavior. Default, Printing is enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	// Configure print behavior. Default, Printing is enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	// +kubebuilder:validation:Optional
	Printing *string `json:"printing,omitempty" tf:"printing,omitempty"`

	// (String) Configure upload behavior. If this field is absent, uploading remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	// Configure upload behavior. If this field is absent, uploading remains enabled. Applies only when version == "v2".
	// Available values: "enabled", "disabled".
	// +kubebuilder:validation:Optional
	Upload *string `json:"upload,omitempty" tf:"upload,omitempty"`

	// only).
	// Indicate which version of the browser isolation controls should apply.
	// Available values: "v1", "v2".
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type BlockPageInitParameters struct {

	// (Boolean) Specify whether to pass the context information as query parameters.
	// Specify whether to pass the context information as query parameters.
	IncludeContext *bool `json:"includeContext,omitempty" tf:"include_context,omitempty"`

	// (String) Specify the URI to which the user is redirected.
	// Specify the URI to which the user is redirected.
	TargetURI *string `json:"targetUri,omitempty" tf:"target_uri,omitempty"`
}

type BlockPageObservation struct {

	// (Boolean) Specify whether to pass the context information as query parameters.
	// Specify whether to pass the context information as query parameters.
	IncludeContext *bool `json:"includeContext,omitempty" tf:"include_context,omitempty"`

	// (String) Specify the URI to which the user is redirected.
	// Specify the URI to which the user is redirected.
	TargetURI *string `json:"targetUri,omitempty" tf:"target_uri,omitempty"`
}

type BlockPageParameters struct {

	// (Boolean) Specify whether to pass the context information as query parameters.
	// Specify whether to pass the context information as query parameters.
	// +kubebuilder:validation:Optional
	IncludeContext *bool `json:"includeContext,omitempty" tf:"include_context,omitempty"`

	// (String) Specify the URI to which the user is redirected.
	// Specify the URI to which the user is redirected.
	// +kubebuilder:validation:Optional
	TargetURI *string `json:"targetUri" tf:"target_uri,omitempty"`
}

type CheckSessionInitParameters struct {

	// (Number) Defines the default duration a policy active in minutes. Must set in order to use the reset_expiration endpoint on this rule.
	// Sets the required session freshness threshold. The API returns a normalized version of this value.
	Duration *string `json:"duration,omitempty" tf:"duration,omitempty"`

	// (Boolean) Enable session enforcement.
	// Enable session enforcement.
	Enforce *bool `json:"enforce,omitempty" tf:"enforce,omitempty"`
}

type CheckSessionObservation struct {

	// (Number) Defines the default duration a policy active in minutes. Must set in order to use the reset_expiration endpoint on this rule.
	// Sets the required session freshness threshold. The API returns a normalized version of this value.
	Duration *string `json:"duration,omitempty" tf:"duration,omitempty"`

	// (Boolean) Enable session enforcement.
	// Enable session enforcement.
	Enforce *bool `json:"enforce,omitempty" tf:"enforce,omitempty"`
}

type CheckSessionParameters struct {

	// (Number) Defines the default duration a policy active in minutes. Must set in order to use the reset_expiration endpoint on this rule.
	// Sets the required session freshness threshold. The API returns a normalized version of this value.
	// +kubebuilder:validation:Optional
	Duration *string `json:"duration,omitempty" tf:"duration,omitempty"`

	// (Boolean) Enable session enforcement.
	// Enable session enforcement.
	// +kubebuilder:validation:Optional
	Enforce *bool `json:"enforce,omitempty" tf:"enforce,omitempty"`
}

type DNSResolversIPv4InitParameters struct {

	// (String) Specify the IPv4 address of the upstream resolver.
	// Specify the IPv4 address of the upstream resolver.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (Number) Specify a port number to use for the upstream resolver. Defaults to 53 if unspecified.
	// Specify a port number to use for the upstream resolver. Defaults to 53 if unspecified.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (Boolean) Indicate whether to connect to this resolver over a private network. Must set when vnet_id set.
	// Indicate whether to connect to this resolver over a private network. Must set when vnet_id set.
	RouteThroughPrivateNetwork *bool `json:"routeThroughPrivateNetwork,omitempty" tf:"route_through_private_network,omitempty"`

	// (String) Specify an optional virtual network for this resolver. Uses default virtual network id if omitted.
	// Specify an optional virtual network for this resolver. Uses default virtual network id if omitted.
	VnetID *string `json:"vnetId,omitempty" tf:"vnet_id,omitempty"`
}

type DNSResolversIPv4Observation struct {

	// (String) Specify the IPv4 address of the upstream resolver.
	// Specify the IPv4 address of the upstream resolver.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (Number) Specify a port number to use for the upstream resolver. Defaults to 53 if unspecified.
	// Specify a port number to use for the upstream resolver. Defaults to 53 if unspecified.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (Boolean) Indicate whether to connect to this resolver over a private network. Must set when vnet_id set.
	// Indicate whether to connect to this resolver over a private network. Must set when vnet_id set.
	RouteThroughPrivateNetwork *bool `json:"routeThroughPrivateNetwork,omitempty" tf:"route_through_private_network,omitempty"`

	// (String) Specify an optional virtual network for this resolver. Uses default virtual network id if omitted.
	// Specify an optional virtual network for this resolver. Uses default virtual network id if omitted.
	VnetID *string `json:"vnetId,omitempty" tf:"vnet_id,omitempty"`
}

type DNSResolversIPv4Parameters struct {

	// (String) Specify the IPv4 address of the upstream resolver.
	// Specify the IPv4 address of the upstream resolver.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip" tf:"ip,omitempty"`

	// (Number) Specify a port number to use for the upstream resolver. Defaults to 53 if unspecified.
	// Specify a port number to use for the upstream resolver. Defaults to 53 if unspecified.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (Boolean) Indicate whether to connect to this resolver over a private network. Must set when vnet_id set.
	// Indicate whether to connect to this resolver over a private network. Must set when vnet_id set.
	// +kubebuilder:validation:Optional
	RouteThroughPrivateNetwork *bool `json:"routeThroughPrivateNetwork,omitempty" tf:"route_through_private_network,omitempty"`

	// (String) Specify an optional virtual network for this resolver. Uses default virtual network id if omitted.
	// Specify an optional virtual network for this resolver. Uses default virtual network id if omitted.
	// +kubebuilder:validation:Optional
	VnetID *string `json:"vnetId,omitempty" tf:"vnet_id,omitempty"`
}

type DNSResolversIPv6InitParameters struct {

	// (String) Specify the IPv4 address of the upstream resolver.
	// Specify the IPv6 address of the upstream resolver.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (Number) Specify a port number to use for the upstream resolver. Defaults to 53 if unspecified.
	// Specify a port number to use for the upstream resolver. Defaults to 53 if unspecified.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (Boolean) Indicate whether to connect to this resolver over a private network. Must set when vnet_id set.
	// Indicate whether to connect to this resolver over a private network. Must set when vnet_id set.
	RouteThroughPrivateNetwork *bool `json:"routeThroughPrivateNetwork,omitempty" tf:"route_through_private_network,omitempty"`

	// (String) Specify an optional virtual network for this resolver. Uses default virtual network id if omitted.
	// Specify an optional virtual network for this resolver. Uses default virtual network id if omitted.
	VnetID *string `json:"vnetId,omitempty" tf:"vnet_id,omitempty"`
}

type DNSResolversIPv6Observation struct {

	// (String) Specify the IPv4 address of the upstream resolver.
	// Specify the IPv6 address of the upstream resolver.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (Number) Specify a port number to use for the upstream resolver. Defaults to 53 if unspecified.
	// Specify a port number to use for the upstream resolver. Defaults to 53 if unspecified.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (Boolean) Indicate whether to connect to this resolver over a private network. Must set when vnet_id set.
	// Indicate whether to connect to this resolver over a private network. Must set when vnet_id set.
	RouteThroughPrivateNetwork *bool `json:"routeThroughPrivateNetwork,omitempty" tf:"route_through_private_network,omitempty"`

	// (String) Specify an optional virtual network for this resolver. Uses default virtual network id if omitted.
	// Specify an optional virtual network for this resolver. Uses default virtual network id if omitted.
	VnetID *string `json:"vnetId,omitempty" tf:"vnet_id,omitempty"`
}

type DNSResolversIPv6Parameters struct {

	// (String) Specify the IPv4 address of the upstream resolver.
	// Specify the IPv6 address of the upstream resolver.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip" tf:"ip,omitempty"`

	// (Number) Specify a port number to use for the upstream resolver. Defaults to 53 if unspecified.
	// Specify a port number to use for the upstream resolver. Defaults to 53 if unspecified.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (Boolean) Indicate whether to connect to this resolver over a private network. Must set when vnet_id set.
	// Indicate whether to connect to this resolver over a private network. Must set when vnet_id set.
	// +kubebuilder:validation:Optional
	RouteThroughPrivateNetwork *bool `json:"routeThroughPrivateNetwork,omitempty" tf:"route_through_private_network,omitempty"`

	// (String) Specify an optional virtual network for this resolver. Uses default virtual network id if omitted.
	// Specify an optional virtual network for this resolver. Uses default virtual network id if omitted.
	// +kubebuilder:validation:Optional
	VnetID *string `json:"vnetId,omitempty" tf:"vnet_id,omitempty"`
}

type DNSResolversInitParameters struct {

	// (Attributes List) (see below for nested schema)
	IPv4 []DNSResolversIPv4InitParameters `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// (Attributes List) (see below for nested schema)
	IPv6 []DNSResolversIPv6InitParameters `json:"ipv6,omitempty" tf:"ipv6,omitempty"`
}

type DNSResolversObservation struct {

	// (Attributes List) (see below for nested schema)
	IPv4 []DNSResolversIPv4Observation `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// (Attributes List) (see below for nested schema)
	IPv6 []DNSResolversIPv6Observation `json:"ipv6,omitempty" tf:"ipv6,omitempty"`
}

type DNSResolversParameters struct {

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPv4 []DNSResolversIPv4Parameters `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPv6 []DNSResolversIPv6Parameters `json:"ipv6,omitempty" tf:"ipv6,omitempty"`
}

type EgressInitParameters struct {

	// (Attributes List) (see below for nested schema)
	// Specify the IPv4 address to use for egress.
	IPv4 *string `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// (String) Specify the fallback IPv4 address to use for egress when the primary IPv4 fails. Set '0.0.0.0' to indicate local egress via WARP IPs.
	// Specify the fallback IPv4 address to use for egress when the primary IPv4 fails. Set '0.0.0.0' to indicate local egress via WARP IPs.
	IPv4Fallback *string `json:"ipv4Fallback,omitempty" tf:"ipv4_fallback,omitempty"`

	// (Attributes List) (see below for nested schema)
	// Specify the IPv6 range to use for egress.
	IPv6 *string `json:"ipv6,omitempty" tf:"ipv6,omitempty"`
}

type EgressObservation struct {

	// (Attributes List) (see below for nested schema)
	// Specify the IPv4 address to use for egress.
	IPv4 *string `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// (String) Specify the fallback IPv4 address to use for egress when the primary IPv4 fails. Set '0.0.0.0' to indicate local egress via WARP IPs.
	// Specify the fallback IPv4 address to use for egress when the primary IPv4 fails. Set '0.0.0.0' to indicate local egress via WARP IPs.
	IPv4Fallback *string `json:"ipv4Fallback,omitempty" tf:"ipv4_fallback,omitempty"`

	// (Attributes List) (see below for nested schema)
	// Specify the IPv6 range to use for egress.
	IPv6 *string `json:"ipv6,omitempty" tf:"ipv6,omitempty"`
}

type EgressParameters struct {

	// (Attributes List) (see below for nested schema)
	// Specify the IPv4 address to use for egress.
	// +kubebuilder:validation:Optional
	IPv4 *string `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// (String) Specify the fallback IPv4 address to use for egress when the primary IPv4 fails. Set '0.0.0.0' to indicate local egress via WARP IPs.
	// Specify the fallback IPv4 address to use for egress when the primary IPv4 fails. Set '0.0.0.0' to indicate local egress via WARP IPs.
	// +kubebuilder:validation:Optional
	IPv4Fallback *string `json:"ipv4Fallback,omitempty" tf:"ipv4_fallback,omitempty"`

	// (Attributes List) (see below for nested schema)
	// Specify the IPv6 range to use for egress.
	// +kubebuilder:validation:Optional
	IPv6 *string `json:"ipv6,omitempty" tf:"ipv6,omitempty"`
}

type ExpirationInitParameters struct {

	// (Number) Defines the default duration a policy active in minutes. Must set in order to use the reset_expiration endpoint on this rule.
	// Defines the default duration a policy active in minutes. Must set in order to use the `reset_expiration` endpoint on this rule.
	Duration *float64 `json:"duration,omitempty" tf:"duration,omitempty"`

	// zero offsets but converts them to the equivalent UTC+00:00  value and returns timestamps with a trailing Z. Expiration policies ignore client  timezones and expire globally at the specified expires_at time.
	// Show the timestamp when the policy expires and stops applying.  The value must follow RFC 3339 and include a UTC offset.  The system accepts non-zero offsets but converts them to the equivalent UTC+00:00  value and returns timestamps with a trailing Z. Expiration policies ignore client  timezones and expire globally at the specified expires_at time.
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`
}

type ExpirationObservation struct {

	// (Number) Defines the default duration a policy active in minutes. Must set in order to use the reset_expiration endpoint on this rule.
	// Defines the default duration a policy active in minutes. Must set in order to use the `reset_expiration` endpoint on this rule.
	Duration *float64 `json:"duration,omitempty" tf:"duration,omitempty"`

	// (Boolean) Indicates whether the policy is expired.
	// Indicates whether the policy is expired.
	Expired *bool `json:"expired,omitempty" tf:"expired,omitempty"`

	// zero offsets but converts them to the equivalent UTC+00:00  value and returns timestamps with a trailing Z. Expiration policies ignore client  timezones and expire globally at the specified expires_at time.
	// Show the timestamp when the policy expires and stops applying.  The value must follow RFC 3339 and include a UTC offset.  The system accepts non-zero offsets but converts them to the equivalent UTC+00:00  value and returns timestamps with a trailing Z. Expiration policies ignore client  timezones and expire globally at the specified expires_at time.
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`
}

type ExpirationParameters struct {

	// (Number) Defines the default duration a policy active in minutes. Must set in order to use the reset_expiration endpoint on this rule.
	// Defines the default duration a policy active in minutes. Must set in order to use the `reset_expiration` endpoint on this rule.
	// +kubebuilder:validation:Optional
	Duration *float64 `json:"duration,omitempty" tf:"duration,omitempty"`

	// zero offsets but converts them to the equivalent UTC+00:00  value and returns timestamps with a trailing Z. Expiration policies ignore client  timezones and expire globally at the specified expires_at time.
	// Show the timestamp when the policy expires and stops applying.  The value must follow RFC 3339 and include a UTC offset.  The system accepts non-zero offsets but converts them to the equivalent UTC+00:00  value and returns timestamps with a trailing Z. Expiration policies ignore client  timezones and expire globally at the specified expires_at time.
	// +kubebuilder:validation:Optional
	ExpiresAt *string `json:"expiresAt" tf:"expires_at,omitempty"`
}

type ForensicCopyInitParameters struct {

	// (Boolean) Specify whether the rule is enabled.
	// Enable sending the copy to storage.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type ForensicCopyObservation struct {

	// (Boolean) Specify whether the rule is enabled.
	// Enable sending the copy to storage.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type ForensicCopyParameters struct {

	// (Boolean) Specify whether the rule is enabled.
	// Enable sending the copy to storage.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type L4OverrideInitParameters struct {

	// (String) Specify the IPv4 address of the upstream resolver.
	// Defines the IPv4 or IPv6 address.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (Number) Specify a port number to use for the upstream resolver. Defaults to 53 if unspecified.
	// Defines a port number to use for TCP/UDP overrides.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type L4OverrideObservation struct {

	// (String) Specify the IPv4 address of the upstream resolver.
	// Defines the IPv4 or IPv6 address.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (Number) Specify a port number to use for the upstream resolver. Defaults to 53 if unspecified.
	// Defines a port number to use for TCP/UDP overrides.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type L4OverrideParameters struct {

	// (String) Specify the IPv4 address of the upstream resolver.
	// Defines the IPv4 or IPv6 address.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (Number) Specify a port number to use for the upstream resolver. Defaults to 53 if unspecified.
	// Defines a port number to use for TCP/UDP overrides.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type NotificationSettingsInitParameters struct {

	// (Boolean) Specify whether the rule is enabled.
	// Enable notification.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Specify whether to pass the context information as query parameters.
	// Indicates whether to pass the context information as query parameters.
	IncludeContext *bool `json:"includeContext,omitempty" tf:"include_context,omitempty"`

	// (String) Customize the message shown in the notification.
	// Customize the message shown in the notification.
	Msg *string `json:"msg,omitempty" tf:"msg,omitempty"`

	// (String) Defines an optional URL to direct users to additional information. If unset, the notification opens a block page.
	// Defines an optional URL to direct users to additional information. If unset, the notification opens a block page.
	SupportURL *string `json:"supportUrl,omitempty" tf:"support_url,omitempty"`
}

type NotificationSettingsObservation struct {

	// (Boolean) Specify whether the rule is enabled.
	// Enable notification.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Specify whether to pass the context information as query parameters.
	// Indicates whether to pass the context information as query parameters.
	IncludeContext *bool `json:"includeContext,omitempty" tf:"include_context,omitempty"`

	// (String) Customize the message shown in the notification.
	// Customize the message shown in the notification.
	Msg *string `json:"msg,omitempty" tf:"msg,omitempty"`

	// (String) Defines an optional URL to direct users to additional information. If unset, the notification opens a block page.
	// Defines an optional URL to direct users to additional information. If unset, the notification opens a block page.
	SupportURL *string `json:"supportUrl,omitempty" tf:"support_url,omitempty"`
}

type NotificationSettingsParameters struct {

	// (Boolean) Specify whether the rule is enabled.
	// Enable notification.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Specify whether to pass the context information as query parameters.
	// Indicates whether to pass the context information as query parameters.
	// +kubebuilder:validation:Optional
	IncludeContext *bool `json:"includeContext,omitempty" tf:"include_context,omitempty"`

	// (String) Customize the message shown in the notification.
	// Customize the message shown in the notification.
	// +kubebuilder:validation:Optional
	Msg *string `json:"msg,omitempty" tf:"msg,omitempty"`

	// (String) Defines an optional URL to direct users to additional information. If unset, the notification opens a block page.
	// Defines an optional URL to direct users to additional information. If unset, the notification opens a block page.
	// +kubebuilder:validation:Optional
	SupportURL *string `json:"supportUrl,omitempty" tf:"support_url,omitempty"`
}

type PayloadLogInitParameters struct {

	// (Boolean) Specify whether the rule is enabled.
	// Enable DLP payload logging for this rule.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type PayloadLogObservation struct {

	// (Boolean) Specify whether the rule is enabled.
	// Enable DLP payload logging for this rule.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type PayloadLogParameters struct {

	// (Boolean) Specify whether the rule is enabled.
	// Enable DLP payload logging for this rule.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type QuarantineInitParameters struct {

	// (List of String) Specify the types of files to sandbox.
	// Specify the types of files to sandbox.
	FileTypes []*string `json:"fileTypes,omitempty" tf:"file_types,omitempty"`
}

type QuarantineObservation struct {

	// (List of String) Specify the types of files to sandbox.
	// Specify the types of files to sandbox.
	FileTypes []*string `json:"fileTypes,omitempty" tf:"file_types,omitempty"`
}

type QuarantineParameters struct {

	// (List of String) Specify the types of files to sandbox.
	// Specify the types of files to sandbox.
	// +kubebuilder:validation:Optional
	FileTypes []*string `json:"fileTypes,omitempty" tf:"file_types,omitempty"`
}

type RedirectInitParameters struct {

	// (Boolean) Specify whether to pass the context information as query parameters.
	// Specify whether to pass the context information as query parameters.
	IncludeContext *bool `json:"includeContext,omitempty" tf:"include_context,omitempty"`

	// (Boolean) Specify whether to append the path and query parameters from the original request to target_uri.
	// Specify whether to append the path and query parameters from the original request to target_uri.
	PreservePathAndQuery *bool `json:"preservePathAndQuery,omitempty" tf:"preserve_path_and_query,omitempty"`

	// (String) Specify the URI to which the user is redirected.
	// Specify the URI to which the user is redirected.
	TargetURI *string `json:"targetUri,omitempty" tf:"target_uri,omitempty"`
}

type RedirectObservation struct {

	// (Boolean) Specify whether to pass the context information as query parameters.
	// Specify whether to pass the context information as query parameters.
	IncludeContext *bool `json:"includeContext,omitempty" tf:"include_context,omitempty"`

	// (Boolean) Specify whether to append the path and query parameters from the original request to target_uri.
	// Specify whether to append the path and query parameters from the original request to target_uri.
	PreservePathAndQuery *bool `json:"preservePathAndQuery,omitempty" tf:"preserve_path_and_query,omitempty"`

	// (String) Specify the URI to which the user is redirected.
	// Specify the URI to which the user is redirected.
	TargetURI *string `json:"targetUri,omitempty" tf:"target_uri,omitempty"`
}

type RedirectParameters struct {

	// (Boolean) Specify whether to pass the context information as query parameters.
	// Specify whether to pass the context information as query parameters.
	// +kubebuilder:validation:Optional
	IncludeContext *bool `json:"includeContext,omitempty" tf:"include_context,omitempty"`

	// (Boolean) Specify whether to append the path and query parameters from the original request to target_uri.
	// Specify whether to append the path and query parameters from the original request to target_uri.
	// +kubebuilder:validation:Optional
	PreservePathAndQuery *bool `json:"preservePathAndQuery,omitempty" tf:"preserve_path_and_query,omitempty"`

	// (String) Specify the URI to which the user is redirected.
	// Specify the URI to which the user is redirected.
	// +kubebuilder:validation:Optional
	TargetURI *string `json:"targetUri" tf:"target_uri,omitempty"`
}

type ResolveDNSInternallyInitParameters struct {

	// (String) Specify the fallback behavior to apply when the internal DNS response code differs from 'NOERROR' or when the response data contains only CNAME records for 'A' or 'AAAA' queries.
	// Available values: "none", "public_dns".
	// Specify the fallback behavior to apply when the internal DNS response code differs from 'NOERROR' or when the response data contains only CNAME records for 'A' or 'AAAA' queries.
	// Available values: "none", "public_dns".
	Fallback *string `json:"fallback,omitempty" tf:"fallback,omitempty"`

	// (String) Specify the internal DNS view identifier to pass to the internal DNS service.
	// Specify the internal DNS view identifier to pass to the internal DNS service.
	ViewID *string `json:"viewId,omitempty" tf:"view_id,omitempty"`
}

type ResolveDNSInternallyObservation struct {

	// (String) Specify the fallback behavior to apply when the internal DNS response code differs from 'NOERROR' or when the response data contains only CNAME records for 'A' or 'AAAA' queries.
	// Available values: "none", "public_dns".
	// Specify the fallback behavior to apply when the internal DNS response code differs from 'NOERROR' or when the response data contains only CNAME records for 'A' or 'AAAA' queries.
	// Available values: "none", "public_dns".
	Fallback *string `json:"fallback,omitempty" tf:"fallback,omitempty"`

	// (String) Specify the internal DNS view identifier to pass to the internal DNS service.
	// Specify the internal DNS view identifier to pass to the internal DNS service.
	ViewID *string `json:"viewId,omitempty" tf:"view_id,omitempty"`
}

type ResolveDNSInternallyParameters struct {

	// (String) Specify the fallback behavior to apply when the internal DNS response code differs from 'NOERROR' or when the response data contains only CNAME records for 'A' or 'AAAA' queries.
	// Available values: "none", "public_dns".
	// Specify the fallback behavior to apply when the internal DNS response code differs from 'NOERROR' or when the response data contains only CNAME records for 'A' or 'AAAA' queries.
	// Available values: "none", "public_dns".
	// +kubebuilder:validation:Optional
	Fallback *string `json:"fallback,omitempty" tf:"fallback,omitempty"`

	// (String) Specify the internal DNS view identifier to pass to the internal DNS service.
	// Specify the internal DNS view identifier to pass to the internal DNS service.
	// +kubebuilder:validation:Optional
	ViewID *string `json:"viewId,omitempty" tf:"view_id,omitempty"`
}

type RuleSettingsInitParameters struct {

	// value pairs. Use header names as keys that map to arrays of header values. Settable only for http rules with the action set to allow.
	// Add custom headers to allowed requests as key-value pairs. Use header names as keys that map to arrays of header values. Settable only for `http` rules with the action set to `allow`.
	AddHeaders map[string][]*string `json:"addHeaders,omitempty" tf:"add_headers,omitempty"`

	// (Boolean) Set to enable MSP children to bypass this rule. Only parent MSP accounts can set this. this rule. Settable for all types of rules.
	// Set to enable MSP children to bypass this rule. Only parent MSP accounts can set this. this rule. Settable for all types of rules.
	AllowChildBypass *bool `json:"allowChildBypass,omitempty" tf:"allow_child_bypass,omitempty"`

	// (Attributes) Define the settings for the Audit SSH action. Settable only for l4 rules with audit_ssh action. (see below for nested schema)
	AuditSSH *AuditSSHInitParameters `json:"auditSsh,omitempty" tf:"audit_ssh,omitempty"`

	// (Attributes) Configure browser isolation behavior. Settable only for http rules with the action set to isolate. (see below for nested schema)
	BisoAdminControls *BisoAdminControlsInitParameters `json:"bisoAdminControls,omitempty" tf:"biso_admin_controls,omitempty"`

	// (Attributes) Configure custom block page settings. If missing or null, use the account settings. Settable only for http rules with the action set to block. (see below for nested schema)
	BlockPage *BlockPageInitParameters `json:"blockPage,omitempty" tf:"block_page,omitempty"`

	// (Boolean) Enable the custom block page. Settable only for dns rules with action block.
	// Enable the custom block page. Settable only for `dns` rules with action `block`.
	BlockPageEnabled *bool `json:"blockPageEnabled,omitempty" tf:"block_page_enabled,omitempty"`

	// (String) Explain why the rule blocks the request. The custom block page shows this text (if enabled). Settable only for dns, l4, and http rules when the action set to block.
	// Explain why the rule blocks the request. The custom block page shows this text (if enabled). Settable only for `dns`, `l4`, and `http` rules when the action set to `block`.
	BlockReason *string `json:"blockReason,omitempty" tf:"block_reason,omitempty"`

	// (Boolean) Set to enable MSP accounts to bypass their parent's rules. Only MSP child accounts can set this. Settable for all types of rules.
	// Set to enable MSP accounts to bypass their parent's rules. Only MSP child accounts can set this. Settable for all types of rules.
	BypassParentRule *bool `json:"bypassParentRule,omitempty" tf:"bypass_parent_rule,omitempty"`

	// (Attributes) Configure session check behavior. Settable only for l4 and http rules with the action set to allow. (see below for nested schema)
	CheckSession *CheckSessionInitParameters `json:"checkSession,omitempty" tf:"check_session,omitempty"`

	// (Attributes) Configure custom resolvers to route queries that match the resolver policy. Unused with 'resolve_dns_through_cloudflare' or 'resolve_dns_internally' settings. DNS queries get routed to the address closest to their origin. Only valid when a rule's action set to 'resolve'. Settable only for dns_resolver rules. (see below for nested schema)
	DNSResolvers *DNSResolversInitParameters `json:"dnsResolvers,omitempty" tf:"dns_resolvers,omitempty"`

	// (Attributes) Configure how Gateway Proxy traffic egresses. You can enable this setting for rules with Egress actions and filters, or omit it to indicate local egress via WARP IPs. Settable only for egress rules. (see below for nested schema)
	Egress *EgressInitParameters `json:"egress,omitempty" tf:"egress,omitempty"`

	// (Attributes) Configure whether a copy of the HTTP request will be sent to storage when the rule matches. (see below for nested schema)
	ForensicCopy *ForensicCopyInitParameters `json:"forensicCopy,omitempty" tf:"forensic_copy,omitempty"`

	// (Boolean) Enable IPs in DNS resolver category blocks. The system blocks only domain name categories unless you enable this setting. Settable only for dns and dns_resolver rules.
	// Enable IPs in DNS resolver category blocks. The system blocks only domain name categories unless you enable this setting. Settable only for `dns` and `dns_resolver` rules.
	IPCategories *bool `json:"ipCategories,omitempty" tf:"ip_categories,omitempty"`

	// (Boolean) Indicates whether to include IPs in DNS resolver indicator feed blocks. Default, indicator feeds block only domain names. Settable only for dns and dns_resolver rules.
	// Indicates whether to include IPs in DNS resolver indicator feed blocks. Default, indicator feeds block only domain names. Settable only for `dns` and `dns_resolver` rules.
	IPIndicatorFeeds *bool `json:"ipIndicatorFeeds,omitempty" tf:"ip_indicator_feeds,omitempty"`

	// (Boolean) Ignore category matches at CNAME domains in a response. When off, evaluate categories in this rule against all CNAME domain categories in the response. Settable only for dns and dns_resolver rules.
	// Ignore category matches at CNAME domains in a response. When off, evaluate categories in this rule against all CNAME domain categories in the response. Settable only for `dns` and `dns_resolver` rules.
	IgnoreCnameCategoryMatches *bool `json:"ignoreCnameCategoryMatches,omitempty" tf:"ignore_cname_category_matches,omitempty"`

	// (Boolean) Specify whether to disable DNSSEC validation (for Allow actions) [INSECURE]. Settable only for dns rules.
	// Specify whether to disable DNSSEC validation (for Allow actions) [INSECURE]. Settable only for `dns` rules.
	InsecureDisableDNSSECValidation *bool `json:"insecureDisableDnssecValidation,omitempty" tf:"insecure_disable_dnssec_validation,omitempty"`

	// (Attributes) Send matching traffic to the supplied destination IP address and port. Settable only for l4 rules with the action set to l4_override. (see below for nested schema)
	L4Override *L4OverrideInitParameters `json:"l4override,omitempty" tf:"l4override,omitempty"`

	// (Attributes) Configure a notification to display on the user's device when this rule matched. Settable for all types of rules with the action set to block. (see below for nested schema)
	NotificationSettings *NotificationSettingsInitParameters `json:"notificationSettings,omitempty" tf:"notification_settings,omitempty"`

	// (String) Defines a hostname for override, for the matching DNS queries. Settable only for dns rules with the action set to override.
	// Defines a hostname for override, for the matching DNS queries. Settable only for `dns` rules with the action set to `override`.
	OverrideHost *string `json:"overrideHost,omitempty" tf:"override_host,omitempty"`

	// (List of String) Defines a an IP or set of IPs for overriding matched DNS queries. Settable only for dns rules with the action set to override.
	// Defines a an IP or set of IPs for overriding matched DNS queries. Settable only for `dns` rules with the action set to `override`.
	OverrideIps []*string `json:"overrideIps,omitempty" tf:"override_ips,omitempty"`

	// (Attributes) Configure DLP payload logging. Settable only for http rules. (see below for nested schema)
	PayloadLog *PayloadLogInitParameters `json:"payloadLog,omitempty" tf:"payload_log,omitempty"`

	// (Attributes) Configure settings that apply to quarantine rules. Settable only for http rules. (see below for nested schema)
	Quarantine *QuarantineInitParameters `json:"quarantine,omitempty" tf:"quarantine,omitempty"`

	// (Attributes) Apply settings to redirect rules. Settable only for http rules with the action set to redirect. (see below for nested schema)
	Redirect *RedirectInitParameters `json:"redirect,omitempty" tf:"redirect,omitempty"`

	// (Attributes) Configure to forward the query to the internal DNS service, passing the specified 'view_id' as input. Not used when 'dns_resolvers' is specified or 'resolve_dns_through_cloudflare' is set. Only valid when a rule's action set to 'resolve'. Settable only for dns_resolver rules. (see below for nested schema)
	ResolveDNSInternally *ResolveDNSInternallyInitParameters `json:"resolveDnsInternally,omitempty" tf:"resolve_dns_internally,omitempty"`

	// (Boolean) Enable to send queries that match the policy to Cloudflare's default 1.1.1.1 DNS resolver. Cannot set when 'dns_resolvers' specified or 'resolve_dns_internally' is set. Only valid when a rule's action set to 'resolve'. Settable only for dns_resolver rules.
	// Enable to send queries that match the policy to Cloudflare's default 1.1.1.1 DNS resolver. Cannot set when 'dns_resolvers' specified or 'resolve_dns_internally' is set. Only valid when a rule's action set to 'resolve'. Settable only for `dns_resolver` rules.
	ResolveDNSThroughCloudflare *bool `json:"resolveDnsThroughCloudflare,omitempty" tf:"resolve_dns_through_cloudflare,omitempty"`

	// (Attributes) Configure behavior when an upstream certificate is invalid or an SSL error occurs. Settable only for http rules with the action set to allow. (see below for nested schema)
	UntrustedCert *UntrustedCertInitParameters `json:"untrustedCert,omitempty" tf:"untrusted_cert,omitempty"`
}

type RuleSettingsObservation struct {

	// value pairs. Use header names as keys that map to arrays of header values. Settable only for http rules with the action set to allow.
	// Add custom headers to allowed requests as key-value pairs. Use header names as keys that map to arrays of header values. Settable only for `http` rules with the action set to `allow`.
	AddHeaders map[string][]*string `json:"addHeaders,omitempty" tf:"add_headers,omitempty"`

	// (Boolean) Set to enable MSP children to bypass this rule. Only parent MSP accounts can set this. this rule. Settable for all types of rules.
	// Set to enable MSP children to bypass this rule. Only parent MSP accounts can set this. this rule. Settable for all types of rules.
	AllowChildBypass *bool `json:"allowChildBypass,omitempty" tf:"allow_child_bypass,omitempty"`

	// (Attributes) Define the settings for the Audit SSH action. Settable only for l4 rules with audit_ssh action. (see below for nested schema)
	AuditSSH *AuditSSHObservation `json:"auditSsh,omitempty" tf:"audit_ssh,omitempty"`

	// (Attributes) Configure browser isolation behavior. Settable only for http rules with the action set to isolate. (see below for nested schema)
	BisoAdminControls *BisoAdminControlsObservation `json:"bisoAdminControls,omitempty" tf:"biso_admin_controls,omitempty"`

	// (Attributes) Configure custom block page settings. If missing or null, use the account settings. Settable only for http rules with the action set to block. (see below for nested schema)
	BlockPage *BlockPageObservation `json:"blockPage,omitempty" tf:"block_page,omitempty"`

	// (Boolean) Enable the custom block page. Settable only for dns rules with action block.
	// Enable the custom block page. Settable only for `dns` rules with action `block`.
	BlockPageEnabled *bool `json:"blockPageEnabled,omitempty" tf:"block_page_enabled,omitempty"`

	// (String) Explain why the rule blocks the request. The custom block page shows this text (if enabled). Settable only for dns, l4, and http rules when the action set to block.
	// Explain why the rule blocks the request. The custom block page shows this text (if enabled). Settable only for `dns`, `l4`, and `http` rules when the action set to `block`.
	BlockReason *string `json:"blockReason,omitempty" tf:"block_reason,omitempty"`

	// (Boolean) Set to enable MSP accounts to bypass their parent's rules. Only MSP child accounts can set this. Settable for all types of rules.
	// Set to enable MSP accounts to bypass their parent's rules. Only MSP child accounts can set this. Settable for all types of rules.
	BypassParentRule *bool `json:"bypassParentRule,omitempty" tf:"bypass_parent_rule,omitempty"`

	// (Attributes) Configure session check behavior. Settable only for l4 and http rules with the action set to allow. (see below for nested schema)
	CheckSession *CheckSessionObservation `json:"checkSession,omitempty" tf:"check_session,omitempty"`

	// (Attributes) Configure custom resolvers to route queries that match the resolver policy. Unused with 'resolve_dns_through_cloudflare' or 'resolve_dns_internally' settings. DNS queries get routed to the address closest to their origin. Only valid when a rule's action set to 'resolve'. Settable only for dns_resolver rules. (see below for nested schema)
	DNSResolvers *DNSResolversObservation `json:"dnsResolvers,omitempty" tf:"dns_resolvers,omitempty"`

	// (Attributes) Configure how Gateway Proxy traffic egresses. You can enable this setting for rules with Egress actions and filters, or omit it to indicate local egress via WARP IPs. Settable only for egress rules. (see below for nested schema)
	Egress *EgressObservation `json:"egress,omitempty" tf:"egress,omitempty"`

	// (Attributes) Configure whether a copy of the HTTP request will be sent to storage when the rule matches. (see below for nested schema)
	ForensicCopy *ForensicCopyObservation `json:"forensicCopy,omitempty" tf:"forensic_copy,omitempty"`

	// (Boolean) Enable IPs in DNS resolver category blocks. The system blocks only domain name categories unless you enable this setting. Settable only for dns and dns_resolver rules.
	// Enable IPs in DNS resolver category blocks. The system blocks only domain name categories unless you enable this setting. Settable only for `dns` and `dns_resolver` rules.
	IPCategories *bool `json:"ipCategories,omitempty" tf:"ip_categories,omitempty"`

	// (Boolean) Indicates whether to include IPs in DNS resolver indicator feed blocks. Default, indicator feeds block only domain names. Settable only for dns and dns_resolver rules.
	// Indicates whether to include IPs in DNS resolver indicator feed blocks. Default, indicator feeds block only domain names. Settable only for `dns` and `dns_resolver` rules.
	IPIndicatorFeeds *bool `json:"ipIndicatorFeeds,omitempty" tf:"ip_indicator_feeds,omitempty"`

	// (Boolean) Ignore category matches at CNAME domains in a response. When off, evaluate categories in this rule against all CNAME domain categories in the response. Settable only for dns and dns_resolver rules.
	// Ignore category matches at CNAME domains in a response. When off, evaluate categories in this rule against all CNAME domain categories in the response. Settable only for `dns` and `dns_resolver` rules.
	IgnoreCnameCategoryMatches *bool `json:"ignoreCnameCategoryMatches,omitempty" tf:"ignore_cname_category_matches,omitempty"`

	// (Boolean) Specify whether to disable DNSSEC validation (for Allow actions) [INSECURE]. Settable only for dns rules.
	// Specify whether to disable DNSSEC validation (for Allow actions) [INSECURE]. Settable only for `dns` rules.
	InsecureDisableDNSSECValidation *bool `json:"insecureDisableDnssecValidation,omitempty" tf:"insecure_disable_dnssec_validation,omitempty"`

	// (Attributes) Send matching traffic to the supplied destination IP address and port. Settable only for l4 rules with the action set to l4_override. (see below for nested schema)
	L4Override *L4OverrideObservation `json:"l4override,omitempty" tf:"l4override,omitempty"`

	// (Attributes) Configure a notification to display on the user's device when this rule matched. Settable for all types of rules with the action set to block. (see below for nested schema)
	NotificationSettings *NotificationSettingsObservation `json:"notificationSettings,omitempty" tf:"notification_settings,omitempty"`

	// (String) Defines a hostname for override, for the matching DNS queries. Settable only for dns rules with the action set to override.
	// Defines a hostname for override, for the matching DNS queries. Settable only for `dns` rules with the action set to `override`.
	OverrideHost *string `json:"overrideHost,omitempty" tf:"override_host,omitempty"`

	// (List of String) Defines a an IP or set of IPs for overriding matched DNS queries. Settable only for dns rules with the action set to override.
	// Defines a an IP or set of IPs for overriding matched DNS queries. Settable only for `dns` rules with the action set to `override`.
	OverrideIps []*string `json:"overrideIps,omitempty" tf:"override_ips,omitempty"`

	// (Attributes) Configure DLP payload logging. Settable only for http rules. (see below for nested schema)
	PayloadLog *PayloadLogObservation `json:"payloadLog,omitempty" tf:"payload_log,omitempty"`

	// (Attributes) Configure settings that apply to quarantine rules. Settable only for http rules. (see below for nested schema)
	Quarantine *QuarantineObservation `json:"quarantine,omitempty" tf:"quarantine,omitempty"`

	// (Attributes) Apply settings to redirect rules. Settable only for http rules with the action set to redirect. (see below for nested schema)
	Redirect *RedirectObservation `json:"redirect,omitempty" tf:"redirect,omitempty"`

	// (Attributes) Configure to forward the query to the internal DNS service, passing the specified 'view_id' as input. Not used when 'dns_resolvers' is specified or 'resolve_dns_through_cloudflare' is set. Only valid when a rule's action set to 'resolve'. Settable only for dns_resolver rules. (see below for nested schema)
	ResolveDNSInternally *ResolveDNSInternallyObservation `json:"resolveDnsInternally,omitempty" tf:"resolve_dns_internally,omitempty"`

	// (Boolean) Enable to send queries that match the policy to Cloudflare's default 1.1.1.1 DNS resolver. Cannot set when 'dns_resolvers' specified or 'resolve_dns_internally' is set. Only valid when a rule's action set to 'resolve'. Settable only for dns_resolver rules.
	// Enable to send queries that match the policy to Cloudflare's default 1.1.1.1 DNS resolver. Cannot set when 'dns_resolvers' specified or 'resolve_dns_internally' is set. Only valid when a rule's action set to 'resolve'. Settable only for `dns_resolver` rules.
	ResolveDNSThroughCloudflare *bool `json:"resolveDnsThroughCloudflare,omitempty" tf:"resolve_dns_through_cloudflare,omitempty"`

	// (Attributes) Configure behavior when an upstream certificate is invalid or an SSL error occurs. Settable only for http rules with the action set to allow. (see below for nested schema)
	UntrustedCert *UntrustedCertObservation `json:"untrustedCert,omitempty" tf:"untrusted_cert,omitempty"`
}

type RuleSettingsParameters struct {

	// value pairs. Use header names as keys that map to arrays of header values. Settable only for http rules with the action set to allow.
	// Add custom headers to allowed requests as key-value pairs. Use header names as keys that map to arrays of header values. Settable only for `http` rules with the action set to `allow`.
	// +kubebuilder:validation:Optional
	AddHeaders map[string][]*string `json:"addHeaders,omitempty" tf:"add_headers,omitempty"`

	// (Boolean) Set to enable MSP children to bypass this rule. Only parent MSP accounts can set this. this rule. Settable for all types of rules.
	// Set to enable MSP children to bypass this rule. Only parent MSP accounts can set this. this rule. Settable for all types of rules.
	// +kubebuilder:validation:Optional
	AllowChildBypass *bool `json:"allowChildBypass,omitempty" tf:"allow_child_bypass,omitempty"`

	// (Attributes) Define the settings for the Audit SSH action. Settable only for l4 rules with audit_ssh action. (see below for nested schema)
	// +kubebuilder:validation:Optional
	AuditSSH *AuditSSHParameters `json:"auditSsh,omitempty" tf:"audit_ssh,omitempty"`

	// (Attributes) Configure browser isolation behavior. Settable only for http rules with the action set to isolate. (see below for nested schema)
	// +kubebuilder:validation:Optional
	BisoAdminControls *BisoAdminControlsParameters `json:"bisoAdminControls,omitempty" tf:"biso_admin_controls,omitempty"`

	// (Attributes) Configure custom block page settings. If missing or null, use the account settings. Settable only for http rules with the action set to block. (see below for nested schema)
	// +kubebuilder:validation:Optional
	BlockPage *BlockPageParameters `json:"blockPage,omitempty" tf:"block_page,omitempty"`

	// (Boolean) Enable the custom block page. Settable only for dns rules with action block.
	// Enable the custom block page. Settable only for `dns` rules with action `block`.
	// +kubebuilder:validation:Optional
	BlockPageEnabled *bool `json:"blockPageEnabled,omitempty" tf:"block_page_enabled,omitempty"`

	// (String) Explain why the rule blocks the request. The custom block page shows this text (if enabled). Settable only for dns, l4, and http rules when the action set to block.
	// Explain why the rule blocks the request. The custom block page shows this text (if enabled). Settable only for `dns`, `l4`, and `http` rules when the action set to `block`.
	// +kubebuilder:validation:Optional
	BlockReason *string `json:"blockReason,omitempty" tf:"block_reason,omitempty"`

	// (Boolean) Set to enable MSP accounts to bypass their parent's rules. Only MSP child accounts can set this. Settable for all types of rules.
	// Set to enable MSP accounts to bypass their parent's rules. Only MSP child accounts can set this. Settable for all types of rules.
	// +kubebuilder:validation:Optional
	BypassParentRule *bool `json:"bypassParentRule,omitempty" tf:"bypass_parent_rule,omitempty"`

	// (Attributes) Configure session check behavior. Settable only for l4 and http rules with the action set to allow. (see below for nested schema)
	// +kubebuilder:validation:Optional
	CheckSession *CheckSessionParameters `json:"checkSession,omitempty" tf:"check_session,omitempty"`

	// (Attributes) Configure custom resolvers to route queries that match the resolver policy. Unused with 'resolve_dns_through_cloudflare' or 'resolve_dns_internally' settings. DNS queries get routed to the address closest to their origin. Only valid when a rule's action set to 'resolve'. Settable only for dns_resolver rules. (see below for nested schema)
	// +kubebuilder:validation:Optional
	DNSResolvers *DNSResolversParameters `json:"dnsResolvers,omitempty" tf:"dns_resolvers,omitempty"`

	// (Attributes) Configure how Gateway Proxy traffic egresses. You can enable this setting for rules with Egress actions and filters, or omit it to indicate local egress via WARP IPs. Settable only for egress rules. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Egress *EgressParameters `json:"egress,omitempty" tf:"egress,omitempty"`

	// (Attributes) Configure whether a copy of the HTTP request will be sent to storage when the rule matches. (see below for nested schema)
	// +kubebuilder:validation:Optional
	ForensicCopy *ForensicCopyParameters `json:"forensicCopy,omitempty" tf:"forensic_copy,omitempty"`

	// (Boolean) Enable IPs in DNS resolver category blocks. The system blocks only domain name categories unless you enable this setting. Settable only for dns and dns_resolver rules.
	// Enable IPs in DNS resolver category blocks. The system blocks only domain name categories unless you enable this setting. Settable only for `dns` and `dns_resolver` rules.
	// +kubebuilder:validation:Optional
	IPCategories *bool `json:"ipCategories,omitempty" tf:"ip_categories,omitempty"`

	// (Boolean) Indicates whether to include IPs in DNS resolver indicator feed blocks. Default, indicator feeds block only domain names. Settable only for dns and dns_resolver rules.
	// Indicates whether to include IPs in DNS resolver indicator feed blocks. Default, indicator feeds block only domain names. Settable only for `dns` and `dns_resolver` rules.
	// +kubebuilder:validation:Optional
	IPIndicatorFeeds *bool `json:"ipIndicatorFeeds,omitempty" tf:"ip_indicator_feeds,omitempty"`

	// (Boolean) Ignore category matches at CNAME domains in a response. When off, evaluate categories in this rule against all CNAME domain categories in the response. Settable only for dns and dns_resolver rules.
	// Ignore category matches at CNAME domains in a response. When off, evaluate categories in this rule against all CNAME domain categories in the response. Settable only for `dns` and `dns_resolver` rules.
	// +kubebuilder:validation:Optional
	IgnoreCnameCategoryMatches *bool `json:"ignoreCnameCategoryMatches,omitempty" tf:"ignore_cname_category_matches,omitempty"`

	// (Boolean) Specify whether to disable DNSSEC validation (for Allow actions) [INSECURE]. Settable only for dns rules.
	// Specify whether to disable DNSSEC validation (for Allow actions) [INSECURE]. Settable only for `dns` rules.
	// +kubebuilder:validation:Optional
	InsecureDisableDNSSECValidation *bool `json:"insecureDisableDnssecValidation,omitempty" tf:"insecure_disable_dnssec_validation,omitempty"`

	// (Attributes) Send matching traffic to the supplied destination IP address and port. Settable only for l4 rules with the action set to l4_override. (see below for nested schema)
	// +kubebuilder:validation:Optional
	L4Override *L4OverrideParameters `json:"l4override,omitempty" tf:"l4override,omitempty"`

	// (Attributes) Configure a notification to display on the user's device when this rule matched. Settable for all types of rules with the action set to block. (see below for nested schema)
	// +kubebuilder:validation:Optional
	NotificationSettings *NotificationSettingsParameters `json:"notificationSettings,omitempty" tf:"notification_settings,omitempty"`

	// (String) Defines a hostname for override, for the matching DNS queries. Settable only for dns rules with the action set to override.
	// Defines a hostname for override, for the matching DNS queries. Settable only for `dns` rules with the action set to `override`.
	// +kubebuilder:validation:Optional
	OverrideHost *string `json:"overrideHost,omitempty" tf:"override_host,omitempty"`

	// (List of String) Defines a an IP or set of IPs for overriding matched DNS queries. Settable only for dns rules with the action set to override.
	// Defines a an IP or set of IPs for overriding matched DNS queries. Settable only for `dns` rules with the action set to `override`.
	// +kubebuilder:validation:Optional
	OverrideIps []*string `json:"overrideIps,omitempty" tf:"override_ips,omitempty"`

	// (Attributes) Configure DLP payload logging. Settable only for http rules. (see below for nested schema)
	// +kubebuilder:validation:Optional
	PayloadLog *PayloadLogParameters `json:"payloadLog,omitempty" tf:"payload_log,omitempty"`

	// (Attributes) Configure settings that apply to quarantine rules. Settable only for http rules. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Quarantine *QuarantineParameters `json:"quarantine,omitempty" tf:"quarantine,omitempty"`

	// (Attributes) Apply settings to redirect rules. Settable only for http rules with the action set to redirect. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Redirect *RedirectParameters `json:"redirect,omitempty" tf:"redirect,omitempty"`

	// (Attributes) Configure to forward the query to the internal DNS service, passing the specified 'view_id' as input. Not used when 'dns_resolvers' is specified or 'resolve_dns_through_cloudflare' is set. Only valid when a rule's action set to 'resolve'. Settable only for dns_resolver rules. (see below for nested schema)
	// +kubebuilder:validation:Optional
	ResolveDNSInternally *ResolveDNSInternallyParameters `json:"resolveDnsInternally,omitempty" tf:"resolve_dns_internally,omitempty"`

	// (Boolean) Enable to send queries that match the policy to Cloudflare's default 1.1.1.1 DNS resolver. Cannot set when 'dns_resolvers' specified or 'resolve_dns_internally' is set. Only valid when a rule's action set to 'resolve'. Settable only for dns_resolver rules.
	// Enable to send queries that match the policy to Cloudflare's default 1.1.1.1 DNS resolver. Cannot set when 'dns_resolvers' specified or 'resolve_dns_internally' is set. Only valid when a rule's action set to 'resolve'. Settable only for `dns_resolver` rules.
	// +kubebuilder:validation:Optional
	ResolveDNSThroughCloudflare *bool `json:"resolveDnsThroughCloudflare,omitempty" tf:"resolve_dns_through_cloudflare,omitempty"`

	// (Attributes) Configure behavior when an upstream certificate is invalid or an SSL error occurs. Settable only for http rules with the action set to allow. (see below for nested schema)
	// +kubebuilder:validation:Optional
	UntrustedCert *UntrustedCertParameters `json:"untrustedCert,omitempty" tf:"untrusted_cert,omitempty"`
}

type ScheduleInitParameters struct {

	// 24:00.  If this parameter omitted, the rule is deactivated on Fridays.
	// Specify the time intervals when the rule is active on Fridays, in the increasing order from 00:00-24:00.  If this parameter omitted, the rule is deactivated on Fridays.
	Fri *string `json:"fri,omitempty" tf:"fri,omitempty"`

	// 24:00(capped at maximum of 6 time splits). If this parameter omitted, the rule is deactivated on Mondays.
	// Specify the time intervals when the rule is active on Mondays, in the increasing order from 00:00-24:00(capped at maximum of 6 time splits). If this parameter omitted, the rule is deactivated on Mondays.
	Mon *string `json:"mon,omitempty" tf:"mon,omitempty"`

	// 24:00.  If this parameter omitted, the rule is deactivated on Saturdays.
	// Specify the time intervals when the rule is active on Saturdays, in the increasing order from 00:00-24:00.  If this parameter omitted, the rule is deactivated on Saturdays.
	Sat *string `json:"sat,omitempty" tf:"sat,omitempty"`

	// 24:00. If this parameter omitted, the rule is deactivated on Sundays.
	// Specify the time intervals when the rule is active on Sundays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Sundays.
	Sun *string `json:"sun,omitempty" tf:"sun,omitempty"`

	// 24:00. If this parameter omitted, the rule is deactivated on Thursdays.
	// Specify the time intervals when the rule is active on Thursdays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Thursdays.
	Thu *string `json:"thu,omitempty" tf:"thu,omitempty"`

	// (String) Specify the time zone for rule evaluation. When a valid time zone city name is provided, Gateway always uses the current time for that time zone. When this parameter is omitted, Gateway uses the time zone determined from the user's IP address. Colo time zone is used when the user's IP address does not resolve to a location.
	// Specify the time zone for rule evaluation. When a [valid time zone city name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List) is provided, Gateway always uses the current time for that time zone. When this parameter is omitted, Gateway uses the time zone determined from the user's IP address. Colo time zone is used when the user's IP address does not resolve to a location.
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`

	// 24:00. If this parameter omitted, the rule is deactivated on Tuesdays.
	// Specify the time intervals when the rule is active on Tuesdays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Tuesdays.
	Tue *string `json:"tue,omitempty" tf:"tue,omitempty"`

	// 24:00. If this parameter omitted, the rule is deactivated on Wednesdays.
	// Specify the time intervals when the rule is active on Wednesdays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Wednesdays.
	Wed *string `json:"wed,omitempty" tf:"wed,omitempty"`
}

type ScheduleObservation struct {

	// 24:00.  If this parameter omitted, the rule is deactivated on Fridays.
	// Specify the time intervals when the rule is active on Fridays, in the increasing order from 00:00-24:00.  If this parameter omitted, the rule is deactivated on Fridays.
	Fri *string `json:"fri,omitempty" tf:"fri,omitempty"`

	// 24:00(capped at maximum of 6 time splits). If this parameter omitted, the rule is deactivated on Mondays.
	// Specify the time intervals when the rule is active on Mondays, in the increasing order from 00:00-24:00(capped at maximum of 6 time splits). If this parameter omitted, the rule is deactivated on Mondays.
	Mon *string `json:"mon,omitempty" tf:"mon,omitempty"`

	// 24:00.  If this parameter omitted, the rule is deactivated on Saturdays.
	// Specify the time intervals when the rule is active on Saturdays, in the increasing order from 00:00-24:00.  If this parameter omitted, the rule is deactivated on Saturdays.
	Sat *string `json:"sat,omitempty" tf:"sat,omitempty"`

	// 24:00. If this parameter omitted, the rule is deactivated on Sundays.
	// Specify the time intervals when the rule is active on Sundays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Sundays.
	Sun *string `json:"sun,omitempty" tf:"sun,omitempty"`

	// 24:00. If this parameter omitted, the rule is deactivated on Thursdays.
	// Specify the time intervals when the rule is active on Thursdays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Thursdays.
	Thu *string `json:"thu,omitempty" tf:"thu,omitempty"`

	// (String) Specify the time zone for rule evaluation. When a valid time zone city name is provided, Gateway always uses the current time for that time zone. When this parameter is omitted, Gateway uses the time zone determined from the user's IP address. Colo time zone is used when the user's IP address does not resolve to a location.
	// Specify the time zone for rule evaluation. When a [valid time zone city name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List) is provided, Gateway always uses the current time for that time zone. When this parameter is omitted, Gateway uses the time zone determined from the user's IP address. Colo time zone is used when the user's IP address does not resolve to a location.
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`

	// 24:00. If this parameter omitted, the rule is deactivated on Tuesdays.
	// Specify the time intervals when the rule is active on Tuesdays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Tuesdays.
	Tue *string `json:"tue,omitempty" tf:"tue,omitempty"`

	// 24:00. If this parameter omitted, the rule is deactivated on Wednesdays.
	// Specify the time intervals when the rule is active on Wednesdays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Wednesdays.
	Wed *string `json:"wed,omitempty" tf:"wed,omitempty"`
}

type ScheduleParameters struct {

	// 24:00.  If this parameter omitted, the rule is deactivated on Fridays.
	// Specify the time intervals when the rule is active on Fridays, in the increasing order from 00:00-24:00.  If this parameter omitted, the rule is deactivated on Fridays.
	// +kubebuilder:validation:Optional
	Fri *string `json:"fri,omitempty" tf:"fri,omitempty"`

	// 24:00(capped at maximum of 6 time splits). If this parameter omitted, the rule is deactivated on Mondays.
	// Specify the time intervals when the rule is active on Mondays, in the increasing order from 00:00-24:00(capped at maximum of 6 time splits). If this parameter omitted, the rule is deactivated on Mondays.
	// +kubebuilder:validation:Optional
	Mon *string `json:"mon,omitempty" tf:"mon,omitempty"`

	// 24:00.  If this parameter omitted, the rule is deactivated on Saturdays.
	// Specify the time intervals when the rule is active on Saturdays, in the increasing order from 00:00-24:00.  If this parameter omitted, the rule is deactivated on Saturdays.
	// +kubebuilder:validation:Optional
	Sat *string `json:"sat,omitempty" tf:"sat,omitempty"`

	// 24:00. If this parameter omitted, the rule is deactivated on Sundays.
	// Specify the time intervals when the rule is active on Sundays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Sundays.
	// +kubebuilder:validation:Optional
	Sun *string `json:"sun,omitempty" tf:"sun,omitempty"`

	// 24:00. If this parameter omitted, the rule is deactivated on Thursdays.
	// Specify the time intervals when the rule is active on Thursdays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Thursdays.
	// +kubebuilder:validation:Optional
	Thu *string `json:"thu,omitempty" tf:"thu,omitempty"`

	// (String) Specify the time zone for rule evaluation. When a valid time zone city name is provided, Gateway always uses the current time for that time zone. When this parameter is omitted, Gateway uses the time zone determined from the user's IP address. Colo time zone is used when the user's IP address does not resolve to a location.
	// Specify the time zone for rule evaluation. When a [valid time zone city name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List) is provided, Gateway always uses the current time for that time zone. When this parameter is omitted, Gateway uses the time zone determined from the user's IP address. Colo time zone is used when the user's IP address does not resolve to a location.
	// +kubebuilder:validation:Optional
	TimeZone *string `json:"timeZone,omitempty" tf:"time_zone,omitempty"`

	// 24:00. If this parameter omitted, the rule is deactivated on Tuesdays.
	// Specify the time intervals when the rule is active on Tuesdays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Tuesdays.
	// +kubebuilder:validation:Optional
	Tue *string `json:"tue,omitempty" tf:"tue,omitempty"`

	// 24:00. If this parameter omitted, the rule is deactivated on Wednesdays.
	// Specify the time intervals when the rule is active on Wednesdays, in the increasing order from 00:00-24:00. If this parameter omitted, the rule is deactivated on Wednesdays.
	// +kubebuilder:validation:Optional
	Wed *string `json:"wed,omitempty" tf:"wed,omitempty"`
}

type TrustGatewayPolicyInitParameters struct {

	// (String)
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) Specify the action to perform when the associated traffic, identity, and device posture expressions either absent or evaluate to true.
	// Available values: "on", "off", "allow", "block", "scan", "noscan", "safesearch", "ytrestricted", "isolate", "noisolate", "override", "l4_override", "egress", "resolve", "quarantine", "redirect".
	// Specify the action to perform when the associated traffic, identity, and device posture expressions either absent or evaluate to `true`.
	// Available values: "on", "off", "allow", "block", "scan", "noscan", "safesearch", "ytrestricted", "isolate", "noisolate", "override", "l4_override", "egress", "resolve", "quarantine", "redirect".
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (String) Specify the rule description.
	// Specify the rule description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Specify the wirefilter expression used for device posture check. The API automatically formats and sanitizes expressions before storing them.
	// Specify the wirefilter expression used for device posture check. The API automatically formats and sanitizes expressions before storing them.
	DevicePosture *string `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	// (Boolean) Specify whether the rule is enabled.
	// Specify whether the rule is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Attributes) Defines the expiration time stamp and default duration of a DNS policy. Takes precedence over the policy's schedule configuration, if any. This  does not apply to HTTP or network policies. Settable only for dns rules. (see below for nested schema)
	Expiration *ExpirationInitParameters `json:"expiration,omitempty" tf:"expiration,omitempty"`

	// (List of String) Specify the protocol or layer to evaluate the traffic, identity, and device posture expressions. Can only contain a single value.
	// Specify the protocol or layer to evaluate the traffic, identity, and device posture expressions. Can only contain a single value.
	Filters []*string `json:"filters,omitempty" tf:"filters,omitempty"`

	// (String) Specify the wirefilter expression used for identity matching. The API automatically formats and sanitizes expressions before storing them.
	// Specify the wirefilter expression used for identity matching. The API automatically formats and sanitizes expressions before storing them.
	Identity *string `json:"identity,omitempty" tf:"identity,omitempty"`

	// (String) Specify the rule name.
	// Specify the rule name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Set the order of your rules. Lower values indicate higher precedence. At each processing phase, evaluate applicable rules in ascending order of this value.
	// Set the order of your rules. Lower values indicate higher precedence. At each processing phase, evaluate applicable rules in ascending order of this value. Refer to [Order of enforcement](http://developers.cloudflare.
	Precedence *float64 `json:"precedence,omitempty" tf:"precedence,omitempty"`

	// returned values in your configuration to prevent drift. (see below for nested schema)
	RuleSettings *RuleSettingsInitParameters `json:"ruleSettings,omitempty" tf:"rule_settings,omitempty"`

	// (Attributes) Defines the schedule for activating DNS policies. Settable only for dns and dns_resolver rules. (see below for nested schema)
	Schedule *ScheduleInitParameters `json:"schedule,omitempty" tf:"schedule,omitempty"`

	// (String) Specify the wirefilter expression used for traffic matching. The API automatically formats and sanitizes expressions before storing them.
	// Specify the wirefilter expression used for traffic matching. The API automatically formats and sanitizes expressions before storing them.
	Traffic *string `json:"traffic,omitempty" tf:"traffic,omitempty"`
}

type TrustGatewayPolicyObservation struct {

	// (String)
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) Specify the action to perform when the associated traffic, identity, and device posture expressions either absent or evaluate to true.
	// Available values: "on", "off", "allow", "block", "scan", "noscan", "safesearch", "ytrestricted", "isolate", "noisolate", "override", "l4_override", "egress", "resolve", "quarantine", "redirect".
	// Specify the action to perform when the associated traffic, identity, and device posture expressions either absent or evaluate to `true`.
	// Available values: "on", "off", "allow", "block", "scan", "noscan", "safesearch", "ytrestricted", "isolate", "noisolate", "override", "l4_override", "egress", "resolve", "quarantine", "redirect".
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (String)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) Indicate the date of deletion, if any.
	// Indicate the date of deletion, if any.
	DeletedAt *string `json:"deletedAt,omitempty" tf:"deleted_at,omitempty"`

	// (String) Specify the rule description.
	// Specify the rule description.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Specify the wirefilter expression used for device posture check. The API automatically formats and sanitizes expressions before storing them.
	// Specify the wirefilter expression used for device posture check. The API automatically formats and sanitizes expressions before storing them.
	DevicePosture *string `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	// (Boolean) Specify whether the rule is enabled.
	// Specify whether the rule is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Attributes) Defines the expiration time stamp and default duration of a DNS policy. Takes precedence over the policy's schedule configuration, if any. This  does not apply to HTTP or network policies. Settable only for dns rules. (see below for nested schema)
	Expiration *ExpirationObservation `json:"expiration,omitempty" tf:"expiration,omitempty"`

	// (List of String) Specify the protocol or layer to evaluate the traffic, identity, and device posture expressions. Can only contain a single value.
	// Specify the protocol or layer to evaluate the traffic, identity, and device posture expressions. Can only contain a single value.
	Filters []*string `json:"filters,omitempty" tf:"filters,omitempty"`

	// (String) Identify the API resource with a UUID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Specify the wirefilter expression used for identity matching. The API automatically formats and sanitizes expressions before storing them.
	// Specify the wirefilter expression used for identity matching. The API automatically formats and sanitizes expressions before storing them.
	Identity *string `json:"identity,omitempty" tf:"identity,omitempty"`

	// (String) Specify the rule name.
	// Specify the rule name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Set the order of your rules. Lower values indicate higher precedence. At each processing phase, evaluate applicable rules in ascending order of this value.
	// Set the order of your rules. Lower values indicate higher precedence. At each processing phase, evaluate applicable rules in ascending order of this value. Refer to [Order of enforcement](http://developers.cloudflare.
	Precedence *float64 `json:"precedence,omitempty" tf:"precedence,omitempty"`

	// (Boolean) Indicate that this rule is shared via the Orgs API and read only.
	// Indicate that this rule is shared via the Orgs API and read only.
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// returned values in your configuration to prevent drift. (see below for nested schema)
	RuleSettings *RuleSettingsObservation `json:"ruleSettings,omitempty" tf:"rule_settings,omitempty"`

	// (Attributes) Defines the schedule for activating DNS policies. Settable only for dns and dns_resolver rules. (see below for nested schema)
	Schedule *ScheduleObservation `json:"schedule,omitempty" tf:"schedule,omitempty"`

	// (Boolean) Indicate that this rule is sharable via the Orgs API.
	// Indicate that this rule is sharable via the Orgs API.
	Sharable *bool `json:"sharable,omitempty" tf:"sharable,omitempty"`

	// (String) Provide the account tag of the account that created the rule.
	// Provide the account tag of the account that created the rule.
	SourceAccount *string `json:"sourceAccount,omitempty" tf:"source_account,omitempty"`

	// (String) Specify the wirefilter expression used for traffic matching. The API automatically formats and sanitizes expressions before storing them.
	// Specify the wirefilter expression used for traffic matching. The API automatically formats and sanitizes expressions before storing them.
	Traffic *string `json:"traffic,omitempty" tf:"traffic,omitempty"`

	// (String)
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// only).
	// Indicate the version number of the rule(read-only).
	Version *float64 `json:"version,omitempty" tf:"version,omitempty"`

	// (String) Indicate a warning for a misconfigured rule, if any.
	// Indicate a warning for a misconfigured rule, if any.
	WarningStatus *string `json:"warningStatus,omitempty" tf:"warning_status,omitempty"`
}

type TrustGatewayPolicyParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) Specify the action to perform when the associated traffic, identity, and device posture expressions either absent or evaluate to true.
	// Available values: "on", "off", "allow", "block", "scan", "noscan", "safesearch", "ytrestricted", "isolate", "noisolate", "override", "l4_override", "egress", "resolve", "quarantine", "redirect".
	// Specify the action to perform when the associated traffic, identity, and device posture expressions either absent or evaluate to `true`.
	// Available values: "on", "off", "allow", "block", "scan", "noscan", "safesearch", "ytrestricted", "isolate", "noisolate", "override", "l4_override", "egress", "resolve", "quarantine", "redirect".
	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (String) Specify the rule description.
	// Specify the rule description.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Specify the wirefilter expression used for device posture check. The API automatically formats and sanitizes expressions before storing them.
	// Specify the wirefilter expression used for device posture check. The API automatically formats and sanitizes expressions before storing them.
	// +kubebuilder:validation:Optional
	DevicePosture *string `json:"devicePosture,omitempty" tf:"device_posture,omitempty"`

	// (Boolean) Specify whether the rule is enabled.
	// Specify whether the rule is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Attributes) Defines the expiration time stamp and default duration of a DNS policy. Takes precedence over the policy's schedule configuration, if any. This  does not apply to HTTP or network policies. Settable only for dns rules. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Expiration *ExpirationParameters `json:"expiration,omitempty" tf:"expiration,omitempty"`

	// (List of String) Specify the protocol or layer to evaluate the traffic, identity, and device posture expressions. Can only contain a single value.
	// Specify the protocol or layer to evaluate the traffic, identity, and device posture expressions. Can only contain a single value.
	// +kubebuilder:validation:Optional
	Filters []*string `json:"filters,omitempty" tf:"filters,omitempty"`

	// (String) Specify the wirefilter expression used for identity matching. The API automatically formats and sanitizes expressions before storing them.
	// Specify the wirefilter expression used for identity matching. The API automatically formats and sanitizes expressions before storing them.
	// +kubebuilder:validation:Optional
	Identity *string `json:"identity,omitempty" tf:"identity,omitempty"`

	// (String) Specify the rule name.
	// Specify the rule name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Set the order of your rules. Lower values indicate higher precedence. At each processing phase, evaluate applicable rules in ascending order of this value.
	// Set the order of your rules. Lower values indicate higher precedence. At each processing phase, evaluate applicable rules in ascending order of this value. Refer to [Order of enforcement](http://developers.cloudflare.
	// +kubebuilder:validation:Optional
	Precedence *float64 `json:"precedence,omitempty" tf:"precedence,omitempty"`

	// returned values in your configuration to prevent drift. (see below for nested schema)
	// +kubebuilder:validation:Optional
	RuleSettings *RuleSettingsParameters `json:"ruleSettings,omitempty" tf:"rule_settings,omitempty"`

	// (Attributes) Defines the schedule for activating DNS policies. Settable only for dns and dns_resolver rules. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Schedule *ScheduleParameters `json:"schedule,omitempty" tf:"schedule,omitempty"`

	// (String) Specify the wirefilter expression used for traffic matching. The API automatically formats and sanitizes expressions before storing them.
	// Specify the wirefilter expression used for traffic matching. The API automatically formats and sanitizes expressions before storing them.
	// +kubebuilder:validation:Optional
	Traffic *string `json:"traffic,omitempty" tf:"traffic,omitempty"`
}

type UntrustedCertInitParameters struct {

	// (String) Specify the action to perform when the associated traffic, identity, and device posture expressions either absent or evaluate to true.
	// Available values: "on", "off", "allow", "block", "scan", "noscan", "safesearch", "ytrestricted", "isolate", "noisolate", "override", "l4_override", "egress", "resolve", "quarantine", "redirect".
	// Defines the action performed when an untrusted certificate seen. The default action an error with HTTP code 526.
	// Available values: "pass_through", "block", "error".
	Action *string `json:"action,omitempty" tf:"action,omitempty"`
}

type UntrustedCertObservation struct {

	// (String) Specify the action to perform when the associated traffic, identity, and device posture expressions either absent or evaluate to true.
	// Available values: "on", "off", "allow", "block", "scan", "noscan", "safesearch", "ytrestricted", "isolate", "noisolate", "override", "l4_override", "egress", "resolve", "quarantine", "redirect".
	// Defines the action performed when an untrusted certificate seen. The default action an error with HTTP code 526.
	// Available values: "pass_through", "block", "error".
	Action *string `json:"action,omitempty" tf:"action,omitempty"`
}

type UntrustedCertParameters struct {

	// (String) Specify the action to perform when the associated traffic, identity, and device posture expressions either absent or evaluate to true.
	// Available values: "on", "off", "allow", "block", "scan", "noscan", "safesearch", "ytrestricted", "isolate", "noisolate", "override", "l4_override", "egress", "resolve", "quarantine", "redirect".
	// Defines the action performed when an untrusted certificate seen. The default action an error with HTTP code 526.
	// Available values: "pass_through", "block", "error".
	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`
}

// TrustGatewayPolicySpec defines the desired state of TrustGatewayPolicy
type TrustGatewayPolicySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TrustGatewayPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TrustGatewayPolicyInitParameters `json:"initProvider,omitempty"`
}

// TrustGatewayPolicyStatus defines the observed state of TrustGatewayPolicy.
type TrustGatewayPolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TrustGatewayPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TrustGatewayPolicy is the Schema for the TrustGatewayPolicys API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,upjet-cloudflare}
type TrustGatewayPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountId) || (has(self.initProvider) && has(self.initProvider.accountId))",message="spec.forProvider.accountId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.action) || (has(self.initProvider) && has(self.initProvider.action))",message="spec.forProvider.action is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   TrustGatewayPolicySpec   `json:"spec"`
	Status TrustGatewayPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TrustGatewayPolicyList contains a list of TrustGatewayPolicys
type TrustGatewayPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TrustGatewayPolicy `json:"items"`
}

// Repository type metadata.
var (
	TrustGatewayPolicy_Kind             = "TrustGatewayPolicy"
	TrustGatewayPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TrustGatewayPolicy_Kind}.String()
	TrustGatewayPolicy_KindAPIVersion   = TrustGatewayPolicy_Kind + "." + CRDGroupVersion.String()
	TrustGatewayPolicy_GroupVersionKind = CRDGroupVersion.WithKind(TrustGatewayPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&TrustGatewayPolicy{}, &TrustGatewayPolicyList{})
}
