// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type TrustDlpPredefinedEntryConfidenceInitParameters struct {
}

type TrustDlpPredefinedEntryConfidenceObservation struct {

	// (Boolean) Indicates whether this entry has AI remote service validation.
	// Indicates whether this entry has AI remote service validation.
	AIContextAvailable *bool `json:"aiContextAvailable,omitempty" tf:"ai_context_available,omitempty"`

	// (Boolean) Indicates whether this entry has any form of validation that is not an AI remote service.
	// Indicates whether this entry has any form of validation that is not an AI remote service.
	Available *bool `json:"available,omitempty" tf:"available,omitempty"`
}

type TrustDlpPredefinedEntryConfidenceParameters struct {
}

type TrustDlpPredefinedEntryInitParameters struct {

	// (String)
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (Boolean)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String)
	EntryID *string `json:"entryId,omitempty" tf:"entry_id,omitempty"`

	// (String) This field is not used as the owning profile.
	// For predefined entries it is already set to a predefined profile.
	// This field is not used as the owning profile.
	// For predefined entries it is already set to a predefined profile.
	ProfileID *string `json:"profileId,omitempty" tf:"profile_id,omitempty"`
}

type TrustDlpPredefinedEntryObservation struct {

	// (String)
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// sensitive manner
	// Cannot be set to false if secret is true
	// Only applies to custom word lists.
	// Determines if the words should be matched in a case-sensitive manner
	// Cannot be set to false if secret is true
	CaseSensitive *bool `json:"caseSensitive,omitempty" tf:"case_sensitive,omitempty"`

	// (Attributes) (see below for nested schema)
	Confidence *TrustDlpPredefinedEntryConfidenceObservation `json:"confidence,omitempty" tf:"confidence,omitempty"`

	// (String)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String)
	EntryID *string `json:"entryId,omitempty" tf:"entry_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) (see below for nested schema)
	Pattern *TrustDlpPredefinedEntryPatternObservation `json:"pattern,omitempty" tf:"pattern,omitempty"`

	// (String) This field is not used as the owning profile.
	// For predefined entries it is already set to a predefined profile.
	// This field is not used as the owning profile.
	// For predefined entries it is already set to a predefined profile.
	ProfileID *string `json:"profileId,omitempty" tf:"profile_id,omitempty"`

	// (Attributes List) (see below for nested schema)
	Profiles []TrustDlpPredefinedEntryProfilesObservation `json:"profiles,omitempty" tf:"profiles,omitempty"`

	// (Boolean)
	Secret *bool `json:"secret,omitempty" tf:"secret,omitempty"`

	// (String) Available values: "custom", "predefined", "integration", "exact_data", "document_fingerprint", "word_list".
	// Available values: "custom", "predefined", "integration", "exact_data", "document_fingerprint", "word_list".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// (String) Available values: "empty", "uploading", "pending", "processing", "failed", "complete".
	// Available values: "empty", "uploading", "pending", "processing", "failed", "complete".
	UploadStatus *string `json:"uploadStatus,omitempty" tf:"upload_status,omitempty"`

	// (Attributes) (see below for nested schema)
	Variant *TrustDlpPredefinedEntryVariantObservation `json:"variant,omitempty" tf:"variant,omitempty"`

	// (String)
	WordList *string `json:"wordList,omitempty" tf:"word_list,omitempty"`
}

type TrustDlpPredefinedEntryParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	EntryID *string `json:"entryId,omitempty" tf:"entry_id,omitempty"`

	// (String) This field is not used as the owning profile.
	// For predefined entries it is already set to a predefined profile.
	// This field is not used as the owning profile.
	// For predefined entries it is already set to a predefined profile.
	// +kubebuilder:validation:Optional
	ProfileID *string `json:"profileId,omitempty" tf:"profile_id,omitempty"`
}

type TrustDlpPredefinedEntryPatternInitParameters struct {
}

type TrustDlpPredefinedEntryPatternObservation struct {

	// (String)
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// (String, Deprecated) Available values: "luhn".
	// Available values: "luhn".
	Validation *string `json:"validation,omitempty" tf:"validation,omitempty"`
}

type TrustDlpPredefinedEntryPatternParameters struct {
}

type TrustDlpPredefinedEntryProfilesInitParameters struct {
}

type TrustDlpPredefinedEntryProfilesObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TrustDlpPredefinedEntryProfilesParameters struct {
}

type TrustDlpPredefinedEntryVariantInitParameters struct {
}

type TrustDlpPredefinedEntryVariantObservation struct {

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Available values: "Intent", "Content".
	// Available values: "Intent", "Content".
	TopicType *string `json:"topicType,omitempty" tf:"topic_type,omitempty"`

	// (String) Available values: "custom", "predefined", "integration", "exact_data", "document_fingerprint", "word_list".
	// Available values: "PromptTopic".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type TrustDlpPredefinedEntryVariantParameters struct {
}

// TrustDlpPredefinedEntrySpec defines the desired state of TrustDlpPredefinedEntry
type TrustDlpPredefinedEntrySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TrustDlpPredefinedEntryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TrustDlpPredefinedEntryInitParameters `json:"initProvider,omitempty"`
}

// TrustDlpPredefinedEntryStatus defines the observed state of TrustDlpPredefinedEntry.
type TrustDlpPredefinedEntryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TrustDlpPredefinedEntryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TrustDlpPredefinedEntry is the Schema for the TrustDlpPredefinedEntrys API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,upjet-cloudflare}
type TrustDlpPredefinedEntry struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountId) || (has(self.initProvider) && has(self.initProvider.accountId))",message="spec.forProvider.accountId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.entryId) || (has(self.initProvider) && has(self.initProvider.entryId))",message="spec.forProvider.entryId is a required parameter"
	Spec   TrustDlpPredefinedEntrySpec   `json:"spec"`
	Status TrustDlpPredefinedEntryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TrustDlpPredefinedEntryList contains a list of TrustDlpPredefinedEntrys
type TrustDlpPredefinedEntryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TrustDlpPredefinedEntry `json:"items"`
}

// Repository type metadata.
var (
	TrustDlpPredefinedEntry_Kind             = "TrustDlpPredefinedEntry"
	TrustDlpPredefinedEntry_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TrustDlpPredefinedEntry_Kind}.String()
	TrustDlpPredefinedEntry_KindAPIVersion   = TrustDlpPredefinedEntry_Kind + "." + CRDGroupVersion.String()
	TrustDlpPredefinedEntry_GroupVersionKind = CRDGroupVersion.WithKind(TrustDlpPredefinedEntry_Kind)
)

func init() {
	SchemeBuilder.Register(&TrustDlpPredefinedEntry{}, &TrustDlpPredefinedEntryList{})
}
