// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Firewall) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Record) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ZoneTransfersACL) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ZoneTransfersIncoming) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ZoneTransfersOutgoing) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ZoneTransfersPeer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ZoneTransfersTsig) Hub() {}
