apiVersion: calls.upjet-cloudflare.m.upbound.io/v1alpha1
kind: SfuApp
metadata:
  annotations:
    meta.upbound.io/example-id: calls/v1alpha1/sfuapp
  labels:
    testing.upbound.io/example-name: example_calls_sfu_app
  name: example-calls-sfu-app
  namespace: crossplane-system
spec:
  forProvider:
    accountId: 023e105f4ecef8ad9ca31a8372d0c353
    name: production-realtime-app
