apiVersion: email.upjet-cloudflare.upbound.io/v1alpha1
kind: SecurityBlockSender
metadata:
  annotations:
    meta.upbound.io/example-id: email/v1alpha1/securityblocksender
  labels:
    testing.upbound.io/example-name: example_email_security_block_sender
  name: example-email-security-block-sender
spec:
  forProvider:
    accountId: 023e105f4ecef8ad9ca31a8372d0c353
    comments: block sender with email test@example.com
    isRegex: false
    pattern: test@example.com
    patternType: EMAIL
