apiVersion: email.upjet-cloudflare.upbound.io/v1alpha1
kind: SecurityImpersonationRegistry
metadata:
  annotations:
    meta.upbound.io/example-id: email/v1alpha1/securityimpersonationregistry
  labels:
    testing.upbound.io/example-name: example_email_security_impersonation_registry
  name: example-email-security-impersonation-registry
spec:
  forProvider:
    accountId: 023e105f4ecef8ad9ca31a8372d0c353
    comments: comments
    directoryId: 0
    directoryNodeId: 0
    email: john.doe@example.com
    externalDirectoryNodeId: external_directory_node_id
    isEmailRegex: false
    name: John Doe
    provenance: A1S_INTERNAL
