apiVersion: email.upjet-cloudflare.upbound.io/v1alpha1
kind: SecurityTrustedDomains
metadata:
  annotations:
    meta.upbound.io/example-id: email/v1alpha1/securitytrusteddomains
  labels:
    testing.upbound.io/example-name: example_email_security_trusted_domains
  name: example-email-security-trusted-domains
spec:
  forProvider:
    accountId: 023e105f4ecef8ad9ca31a8372d0c353
    comments: null
    isRecent: true
    isRegex: false
    isSimilarity: false
    pattern: example.com
