apiVersion: zero.upjet-cloudflare.m.upbound.io/v1alpha1
kind: TrustDlpDataset
metadata:
  annotations:
    meta.upbound.io/example-id: zero/v1alpha1/trustdlpdataset
  labels:
    testing.upbound.io/example-name: example_zero_trust_dlp_dataset
  name: example-zero-trust-dlp-dataset
  namespace: crossplane-system
spec:
  forProvider:
    accountId: account_id
    caseSensitive: true
    description: description
    encodingVersion: 0
    name: name
    secret: true
