apiVersion: zero.upjet-cloudflare.m.upbound.io/v1alpha1
kind: TrustAccessAIControlsMcpServer
metadata:
  annotations:
    meta.upbound.io/example-id: zero/v1alpha1/trustaccessaicontrolsmcpserver
  labels:
    testing.upbound.io/example-name: example_zero_trust_access_ai_controls_mcp_server
  name: example-zero-trust-access-ai-controls-mcp-server
  namespace: crossplane-system
spec:
  forProvider:
    accountId: ${var.cloudflare_account_id}
    authCredentialsSecretRef:
      key: example-key
      name: example-secret
    authType: oauth
    clientSecretSecretRef:
      key: example-key
      name: example-secret
    hostname: https://github-mcp.example.com/mcp
    isSharedOauthCallbackEnabled: true
    name: GitHub MCP Server
