apiVersion: zero.upjet-cloudflare.m.upbound.io/v1alpha1
kind: TrustDlpCustomProfile
metadata:
  annotations:
    meta.upbound.io/example-id: zero/v1alpha1/trustdlpcustomprofile
  labels:
    testing.upbound.io/example-name: example_zero_trust_dlp_custom_profile
  name: example-zero-trust-dlp-custom-profile
  namespace: crossplane-system
spec:
  forProvider:
    accountId: account_id
    aiContextEnabled: true
    allowedMatchCount: 5
    confidenceThreshold: confidence_threshold
    contextAwareness:
      enabled: true
      skip:
        files: true
    dataClasses:
    - 182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e
    dataTags:
    - 182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e
    description: description
    name: name
    ocrEnabled: true
    sensitivityLevels:
    - groupId: 182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e
      levelId: 182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e
    sharedEntries:
    - enabled: true
      entryId: 182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e
