//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnnotationsInitParameters) DeepCopyInto(out *AnnotationsInitParameters) {
	*out = *in
	if in.WorkersMessage != nil {
		in, out := &in.WorkersMessage, &out.WorkersMessage
		*out = new(string)
		**out = **in
	}
	if in.WorkersTag != nil {
		in, out := &in.WorkersTag, &out.WorkersTag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnotationsInitParameters.
func (in *AnnotationsInitParameters) DeepCopy() *AnnotationsInitParameters {
	if in == nil {
		return nil
	}
	out := new(AnnotationsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnnotationsObservation) DeepCopyInto(out *AnnotationsObservation) {
	*out = *in
	if in.WorkersMessage != nil {
		in, out := &in.WorkersMessage, &out.WorkersMessage
		*out = new(string)
		**out = **in
	}
	if in.WorkersTag != nil {
		in, out := &in.WorkersTag, &out.WorkersTag
		*out = new(string)
		**out = **in
	}
	if in.WorkersTriggeredBy != nil {
		in, out := &in.WorkersTriggeredBy, &out.WorkersTriggeredBy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnotationsObservation.
func (in *AnnotationsObservation) DeepCopy() *AnnotationsObservation {
	if in == nil {
		return nil
	}
	out := new(AnnotationsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnnotationsParameters) DeepCopyInto(out *AnnotationsParameters) {
	*out = *in
	if in.WorkersMessage != nil {
		in, out := &in.WorkersMessage, &out.WorkersMessage
		*out = new(string)
		**out = **in
	}
	if in.WorkersTag != nil {
		in, out := &in.WorkersTag, &out.WorkersTag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnotationsParameters.
func (in *AnnotationsParameters) DeepCopy() *AnnotationsParameters {
	if in == nil {
		return nil
	}
	out := new(AnnotationsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssetsInitParameters) DeepCopyInto(out *AssetsInitParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ConfigInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Directory != nil {
		in, out := &in.Directory, &out.Directory
		*out = new(string)
		**out = **in
	}
	if in.JwtSecretRef != nil {
		in, out := &in.JwtSecretRef, &out.JwtSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssetsInitParameters.
func (in *AssetsInitParameters) DeepCopy() *AssetsInitParameters {
	if in == nil {
		return nil
	}
	out := new(AssetsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssetsObservation) DeepCopyInto(out *AssetsObservation) {
	*out = *in
	if in.AssetManifestSha256 != nil {
		in, out := &in.AssetManifestSha256, &out.AssetManifestSha256
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ConfigObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Directory != nil {
		in, out := &in.Directory, &out.Directory
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssetsObservation.
func (in *AssetsObservation) DeepCopy() *AssetsObservation {
	if in == nil {
		return nil
	}
	out := new(AssetsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssetsParameters) DeepCopyInto(out *AssetsParameters) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ConfigParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Directory != nil {
		in, out := &in.Directory, &out.Directory
		*out = new(string)
		**out = **in
	}
	if in.JwtSecretRef != nil {
		in, out := &in.JwtSecretRef, &out.JwtSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssetsParameters.
func (in *AssetsParameters) DeepCopy() *AssetsParameters {
	if in == nil {
		return nil
	}
	out := new(AssetsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindingsInitParameters) DeepCopyInto(out *BindingsInitParameters) {
	*out = *in
	if in.Algorithm != nil {
		in, out := &in.Algorithm, &out.Algorithm
		*out = new(string)
		**out = **in
	}
	if in.AllowedDestinationAddresses != nil {
		in, out := &in.AllowedDestinationAddresses, &out.AllowedDestinationAddresses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowedSenderAddresses != nil {
		in, out := &in.AllowedSenderAddresses, &out.AllowedSenderAddresses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
	if in.CertificateID != nil {
		in, out := &in.CertificateID, &out.CertificateID
		*out = new(string)
		**out = **in
	}
	if in.ClassName != nil {
		in, out := &in.ClassName, &out.ClassName
		*out = new(string)
		**out = **in
	}
	if in.Dataset != nil {
		in, out := &in.Dataset, &out.Dataset
		*out = new(string)
		**out = **in
	}
	if in.DestinationAddress != nil {
		in, out := &in.DestinationAddress, &out.DestinationAddress
		*out = new(string)
		**out = **in
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = new(string)
		**out = **in
	}
	if in.Format != nil {
		in, out := &in.Format, &out.Format
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IndexName != nil {
		in, out := &in.IndexName, &out.IndexName
		*out = new(string)
		**out = **in
	}
	if in.JSON != nil {
		in, out := &in.JSON, &out.JSON
		*out = new(string)
		**out = **in
	}
	if in.Jurisdiction != nil {
		in, out := &in.Jurisdiction, &out.Jurisdiction
		*out = new(string)
		**out = **in
	}
	if in.KeyBase64SecretRef != nil {
		in, out := &in.KeyBase64SecretRef, &out.KeyBase64SecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.KeyJwkSecretRef != nil {
		in, out := &in.KeyJwkSecretRef, &out.KeyJwkSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceID != nil {
		in, out := &in.NamespaceID, &out.NamespaceID
		*out = new(string)
		**out = **in
	}
	if in.OldName != nil {
		in, out := &in.OldName, &out.OldName
		*out = new(string)
		**out = **in
	}
	if in.Outbound != nil {
		in, out := &in.Outbound, &out.Outbound
		*out = new(OutboundInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Part != nil {
		in, out := &in.Part, &out.Part
		*out = new(string)
		**out = **in
	}
	if in.Pipeline != nil {
		in, out := &in.Pipeline, &out.Pipeline
		*out = new(string)
		**out = **in
	}
	if in.QueueName != nil {
		in, out := &in.QueueName, &out.QueueName
		*out = new(string)
		**out = **in
	}
	if in.ScriptName != nil {
		in, out := &in.ScriptName, &out.ScriptName
		*out = new(string)
		**out = **in
	}
	if in.SecretName != nil {
		in, out := &in.SecretName, &out.SecretName
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(string)
		**out = **in
	}
	if in.Simple != nil {
		in, out := &in.Simple, &out.Simple
		*out = new(SimpleInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.StoreID != nil {
		in, out := &in.StoreID, &out.StoreID
		*out = new(string)
		**out = **in
	}
	if in.TextSecretRef != nil {
		in, out := &in.TextSecretRef, &out.TextSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Usages != nil {
		in, out := &in.Usages, &out.Usages
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.VersionID != nil {
		in, out := &in.VersionID, &out.VersionID
		*out = new(string)
		**out = **in
	}
	if in.WorkflowName != nil {
		in, out := &in.WorkflowName, &out.WorkflowName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingsInitParameters.
func (in *BindingsInitParameters) DeepCopy() *BindingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(BindingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindingsObservation) DeepCopyInto(out *BindingsObservation) {
	*out = *in
	if in.Algorithm != nil {
		in, out := &in.Algorithm, &out.Algorithm
		*out = new(string)
		**out = **in
	}
	if in.AllowedDestinationAddresses != nil {
		in, out := &in.AllowedDestinationAddresses, &out.AllowedDestinationAddresses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowedSenderAddresses != nil {
		in, out := &in.AllowedSenderAddresses, &out.AllowedSenderAddresses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
	if in.CertificateID != nil {
		in, out := &in.CertificateID, &out.CertificateID
		*out = new(string)
		**out = **in
	}
	if in.ClassName != nil {
		in, out := &in.ClassName, &out.ClassName
		*out = new(string)
		**out = **in
	}
	if in.Dataset != nil {
		in, out := &in.Dataset, &out.Dataset
		*out = new(string)
		**out = **in
	}
	if in.DestinationAddress != nil {
		in, out := &in.DestinationAddress, &out.DestinationAddress
		*out = new(string)
		**out = **in
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = new(string)
		**out = **in
	}
	if in.Format != nil {
		in, out := &in.Format, &out.Format
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IndexName != nil {
		in, out := &in.IndexName, &out.IndexName
		*out = new(string)
		**out = **in
	}
	if in.JSON != nil {
		in, out := &in.JSON, &out.JSON
		*out = new(string)
		**out = **in
	}
	if in.Jurisdiction != nil {
		in, out := &in.Jurisdiction, &out.Jurisdiction
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceID != nil {
		in, out := &in.NamespaceID, &out.NamespaceID
		*out = new(string)
		**out = **in
	}
	if in.OldName != nil {
		in, out := &in.OldName, &out.OldName
		*out = new(string)
		**out = **in
	}
	if in.Outbound != nil {
		in, out := &in.Outbound, &out.Outbound
		*out = new(OutboundObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Part != nil {
		in, out := &in.Part, &out.Part
		*out = new(string)
		**out = **in
	}
	if in.Pipeline != nil {
		in, out := &in.Pipeline, &out.Pipeline
		*out = new(string)
		**out = **in
	}
	if in.QueueName != nil {
		in, out := &in.QueueName, &out.QueueName
		*out = new(string)
		**out = **in
	}
	if in.ScriptName != nil {
		in, out := &in.ScriptName, &out.ScriptName
		*out = new(string)
		**out = **in
	}
	if in.SecretName != nil {
		in, out := &in.SecretName, &out.SecretName
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(string)
		**out = **in
	}
	if in.Simple != nil {
		in, out := &in.Simple, &out.Simple
		*out = new(SimpleObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.StoreID != nil {
		in, out := &in.StoreID, &out.StoreID
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Usages != nil {
		in, out := &in.Usages, &out.Usages
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.VersionID != nil {
		in, out := &in.VersionID, &out.VersionID
		*out = new(string)
		**out = **in
	}
	if in.WorkflowName != nil {
		in, out := &in.WorkflowName, &out.WorkflowName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingsObservation.
func (in *BindingsObservation) DeepCopy() *BindingsObservation {
	if in == nil {
		return nil
	}
	out := new(BindingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BindingsParameters) DeepCopyInto(out *BindingsParameters) {
	*out = *in
	if in.Algorithm != nil {
		in, out := &in.Algorithm, &out.Algorithm
		*out = new(string)
		**out = **in
	}
	if in.AllowedDestinationAddresses != nil {
		in, out := &in.AllowedDestinationAddresses, &out.AllowedDestinationAddresses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AllowedSenderAddresses != nil {
		in, out := &in.AllowedSenderAddresses, &out.AllowedSenderAddresses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
	if in.CertificateID != nil {
		in, out := &in.CertificateID, &out.CertificateID
		*out = new(string)
		**out = **in
	}
	if in.ClassName != nil {
		in, out := &in.ClassName, &out.ClassName
		*out = new(string)
		**out = **in
	}
	if in.Dataset != nil {
		in, out := &in.Dataset, &out.Dataset
		*out = new(string)
		**out = **in
	}
	if in.DestinationAddress != nil {
		in, out := &in.DestinationAddress, &out.DestinationAddress
		*out = new(string)
		**out = **in
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = new(string)
		**out = **in
	}
	if in.Format != nil {
		in, out := &in.Format, &out.Format
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IndexName != nil {
		in, out := &in.IndexName, &out.IndexName
		*out = new(string)
		**out = **in
	}
	if in.JSON != nil {
		in, out := &in.JSON, &out.JSON
		*out = new(string)
		**out = **in
	}
	if in.Jurisdiction != nil {
		in, out := &in.Jurisdiction, &out.Jurisdiction
		*out = new(string)
		**out = **in
	}
	if in.KeyBase64SecretRef != nil {
		in, out := &in.KeyBase64SecretRef, &out.KeyBase64SecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.KeyJwkSecretRef != nil {
		in, out := &in.KeyJwkSecretRef, &out.KeyJwkSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.NamespaceID != nil {
		in, out := &in.NamespaceID, &out.NamespaceID
		*out = new(string)
		**out = **in
	}
	if in.OldName != nil {
		in, out := &in.OldName, &out.OldName
		*out = new(string)
		**out = **in
	}
	if in.Outbound != nil {
		in, out := &in.Outbound, &out.Outbound
		*out = new(OutboundParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Part != nil {
		in, out := &in.Part, &out.Part
		*out = new(string)
		**out = **in
	}
	if in.Pipeline != nil {
		in, out := &in.Pipeline, &out.Pipeline
		*out = new(string)
		**out = **in
	}
	if in.QueueName != nil {
		in, out := &in.QueueName, &out.QueueName
		*out = new(string)
		**out = **in
	}
	if in.ScriptName != nil {
		in, out := &in.ScriptName, &out.ScriptName
		*out = new(string)
		**out = **in
	}
	if in.SecretName != nil {
		in, out := &in.SecretName, &out.SecretName
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(string)
		**out = **in
	}
	if in.Simple != nil {
		in, out := &in.Simple, &out.Simple
		*out = new(SimpleParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.StoreID != nil {
		in, out := &in.StoreID, &out.StoreID
		*out = new(string)
		**out = **in
	}
	if in.TextSecretRef != nil {
		in, out := &in.TextSecretRef, &out.TextSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Usages != nil {
		in, out := &in.Usages, &out.Usages
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.VersionID != nil {
		in, out := &in.VersionID, &out.VersionID
		*out = new(string)
		**out = **in
	}
	if in.WorkflowName != nil {
		in, out := &in.WorkflowName, &out.WorkflowName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BindingsParameters.
func (in *BindingsParameters) DeepCopy() *BindingsParameters {
	if in == nil {
		return nil
	}
	out := new(BindingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigInitParameters) DeepCopyInto(out *ConfigInitParameters) {
	*out = *in
	if in.HTMLHandling != nil {
		in, out := &in.HTMLHandling, &out.HTMLHandling
		*out = new(string)
		**out = **in
	}
	if in.NotFoundHandling != nil {
		in, out := &in.NotFoundHandling, &out.NotFoundHandling
		*out = new(string)
		**out = **in
	}
	if in.RunWorkerFirst != nil {
		in, out := &in.RunWorkerFirst, &out.RunWorkerFirst
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigInitParameters.
func (in *ConfigInitParameters) DeepCopy() *ConfigInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigObservation) DeepCopyInto(out *ConfigObservation) {
	*out = *in
	if in.HTMLHandling != nil {
		in, out := &in.HTMLHandling, &out.HTMLHandling
		*out = new(string)
		**out = **in
	}
	if in.NotFoundHandling != nil {
		in, out := &in.NotFoundHandling, &out.NotFoundHandling
		*out = new(string)
		**out = **in
	}
	if in.RunWorkerFirst != nil {
		in, out := &in.RunWorkerFirst, &out.RunWorkerFirst
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigObservation.
func (in *ConfigObservation) DeepCopy() *ConfigObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigParameters) DeepCopyInto(out *ConfigParameters) {
	*out = *in
	if in.HTMLHandling != nil {
		in, out := &in.HTMLHandling, &out.HTMLHandling
		*out = new(string)
		**out = **in
	}
	if in.NotFoundHandling != nil {
		in, out := &in.NotFoundHandling, &out.NotFoundHandling
		*out = new(string)
		**out = **in
	}
	if in.RunWorkerFirst != nil {
		in, out := &in.RunWorkerFirst, &out.RunWorkerFirst
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigParameters.
func (in *ConfigParameters) DeepCopy() *ConfigParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitsInitParameters) DeepCopyInto(out *LimitsInitParameters) {
	*out = *in
	if in.CPUMs != nil {
		in, out := &in.CPUMs, &out.CPUMs
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitsInitParameters.
func (in *LimitsInitParameters) DeepCopy() *LimitsInitParameters {
	if in == nil {
		return nil
	}
	out := new(LimitsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitsObservation) DeepCopyInto(out *LimitsObservation) {
	*out = *in
	if in.CPUMs != nil {
		in, out := &in.CPUMs, &out.CPUMs
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitsObservation.
func (in *LimitsObservation) DeepCopy() *LimitsObservation {
	if in == nil {
		return nil
	}
	out := new(LimitsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitsParameters) DeepCopyInto(out *LimitsParameters) {
	*out = *in
	if in.CPUMs != nil {
		in, out := &in.CPUMs, &out.CPUMs
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitsParameters.
func (in *LimitsParameters) DeepCopy() *LimitsParameters {
	if in == nil {
		return nil
	}
	out := new(LimitsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationsInitParameters) DeepCopyInto(out *MigrationsInitParameters) {
	*out = *in
	if in.DeletedClasses != nil {
		in, out := &in.DeletedClasses, &out.DeletedClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NewClasses != nil {
		in, out := &in.NewClasses, &out.NewClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NewSqliteClasses != nil {
		in, out := &in.NewSqliteClasses, &out.NewSqliteClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NewTag != nil {
		in, out := &in.NewTag, &out.NewTag
		*out = new(string)
		**out = **in
	}
	if in.OldTag != nil {
		in, out := &in.OldTag, &out.OldTag
		*out = new(string)
		**out = **in
	}
	if in.RenamedClasses != nil {
		in, out := &in.RenamedClasses, &out.RenamedClasses
		*out = make([]RenamedClassesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]StepsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TransferredClasses != nil {
		in, out := &in.TransferredClasses, &out.TransferredClasses
		*out = make([]MigrationsTransferredClassesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationsInitParameters.
func (in *MigrationsInitParameters) DeepCopy() *MigrationsInitParameters {
	if in == nil {
		return nil
	}
	out := new(MigrationsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationsObservation) DeepCopyInto(out *MigrationsObservation) {
	*out = *in
	if in.DeletedClasses != nil {
		in, out := &in.DeletedClasses, &out.DeletedClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NewClasses != nil {
		in, out := &in.NewClasses, &out.NewClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NewSqliteClasses != nil {
		in, out := &in.NewSqliteClasses, &out.NewSqliteClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NewTag != nil {
		in, out := &in.NewTag, &out.NewTag
		*out = new(string)
		**out = **in
	}
	if in.OldTag != nil {
		in, out := &in.OldTag, &out.OldTag
		*out = new(string)
		**out = **in
	}
	if in.RenamedClasses != nil {
		in, out := &in.RenamedClasses, &out.RenamedClasses
		*out = make([]RenamedClassesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]StepsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TransferredClasses != nil {
		in, out := &in.TransferredClasses, &out.TransferredClasses
		*out = make([]MigrationsTransferredClassesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationsObservation.
func (in *MigrationsObservation) DeepCopy() *MigrationsObservation {
	if in == nil {
		return nil
	}
	out := new(MigrationsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationsParameters) DeepCopyInto(out *MigrationsParameters) {
	*out = *in
	if in.DeletedClasses != nil {
		in, out := &in.DeletedClasses, &out.DeletedClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NewClasses != nil {
		in, out := &in.NewClasses, &out.NewClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NewSqliteClasses != nil {
		in, out := &in.NewSqliteClasses, &out.NewSqliteClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NewTag != nil {
		in, out := &in.NewTag, &out.NewTag
		*out = new(string)
		**out = **in
	}
	if in.OldTag != nil {
		in, out := &in.OldTag, &out.OldTag
		*out = new(string)
		**out = **in
	}
	if in.RenamedClasses != nil {
		in, out := &in.RenamedClasses, &out.RenamedClasses
		*out = make([]RenamedClassesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]StepsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TransferredClasses != nil {
		in, out := &in.TransferredClasses, &out.TransferredClasses
		*out = make([]MigrationsTransferredClassesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationsParameters.
func (in *MigrationsParameters) DeepCopy() *MigrationsParameters {
	if in == nil {
		return nil
	}
	out := new(MigrationsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationsTransferredClassesInitParameters) DeepCopyInto(out *MigrationsTransferredClassesInitParameters) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.FromScript != nil {
		in, out := &in.FromScript, &out.FromScript
		*out = new(string)
		**out = **in
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationsTransferredClassesInitParameters.
func (in *MigrationsTransferredClassesInitParameters) DeepCopy() *MigrationsTransferredClassesInitParameters {
	if in == nil {
		return nil
	}
	out := new(MigrationsTransferredClassesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationsTransferredClassesObservation) DeepCopyInto(out *MigrationsTransferredClassesObservation) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.FromScript != nil {
		in, out := &in.FromScript, &out.FromScript
		*out = new(string)
		**out = **in
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationsTransferredClassesObservation.
func (in *MigrationsTransferredClassesObservation) DeepCopy() *MigrationsTransferredClassesObservation {
	if in == nil {
		return nil
	}
	out := new(MigrationsTransferredClassesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationsTransferredClassesParameters) DeepCopyInto(out *MigrationsTransferredClassesParameters) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.FromScript != nil {
		in, out := &in.FromScript, &out.FromScript
		*out = new(string)
		**out = **in
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationsTransferredClassesParameters.
func (in *MigrationsTransferredClassesParameters) DeepCopy() *MigrationsTransferredClassesParameters {
	if in == nil {
		return nil
	}
	out := new(MigrationsTransferredClassesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModulesInitParameters) DeepCopyInto(out *ModulesInitParameters) {
	*out = *in
	if in.ContentBase64 != nil {
		in, out := &in.ContentBase64, &out.ContentBase64
		*out = new(string)
		**out = **in
	}
	if in.ContentFile != nil {
		in, out := &in.ContentFile, &out.ContentFile
		*out = new(string)
		**out = **in
	}
	if in.ContentType != nil {
		in, out := &in.ContentType, &out.ContentType
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModulesInitParameters.
func (in *ModulesInitParameters) DeepCopy() *ModulesInitParameters {
	if in == nil {
		return nil
	}
	out := new(ModulesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModulesObservation) DeepCopyInto(out *ModulesObservation) {
	*out = *in
	if in.ContentBase64 != nil {
		in, out := &in.ContentBase64, &out.ContentBase64
		*out = new(string)
		**out = **in
	}
	if in.ContentFile != nil {
		in, out := &in.ContentFile, &out.ContentFile
		*out = new(string)
		**out = **in
	}
	if in.ContentSha256 != nil {
		in, out := &in.ContentSha256, &out.ContentSha256
		*out = new(string)
		**out = **in
	}
	if in.ContentType != nil {
		in, out := &in.ContentType, &out.ContentType
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModulesObservation.
func (in *ModulesObservation) DeepCopy() *ModulesObservation {
	if in == nil {
		return nil
	}
	out := new(ModulesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModulesParameters) DeepCopyInto(out *ModulesParameters) {
	*out = *in
	if in.ContentBase64 != nil {
		in, out := &in.ContentBase64, &out.ContentBase64
		*out = new(string)
		**out = **in
	}
	if in.ContentFile != nil {
		in, out := &in.ContentFile, &out.ContentFile
		*out = new(string)
		**out = **in
	}
	if in.ContentType != nil {
		in, out := &in.ContentType, &out.ContentType
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModulesParameters.
func (in *ModulesParameters) DeepCopy() *ModulesParameters {
	if in == nil {
		return nil
	}
	out := new(ModulesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutboundInitParameters) DeepCopyInto(out *OutboundInitParameters) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make([]ParamsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Worker != nil {
		in, out := &in.Worker, &out.Worker
		*out = new(WorkerInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutboundInitParameters.
func (in *OutboundInitParameters) DeepCopy() *OutboundInitParameters {
	if in == nil {
		return nil
	}
	out := new(OutboundInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutboundObservation) DeepCopyInto(out *OutboundObservation) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make([]ParamsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Worker != nil {
		in, out := &in.Worker, &out.Worker
		*out = new(WorkerObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutboundObservation.
func (in *OutboundObservation) DeepCopy() *OutboundObservation {
	if in == nil {
		return nil
	}
	out := new(OutboundObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutboundParameters) DeepCopyInto(out *OutboundParameters) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make([]ParamsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Worker != nil {
		in, out := &in.Worker, &out.Worker
		*out = new(WorkerParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutboundParameters.
func (in *OutboundParameters) DeepCopy() *OutboundParameters {
	if in == nil {
		return nil
	}
	out := new(OutboundParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParamsInitParameters) DeepCopyInto(out *ParamsInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParamsInitParameters.
func (in *ParamsInitParameters) DeepCopy() *ParamsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ParamsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParamsObservation) DeepCopyInto(out *ParamsObservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParamsObservation.
func (in *ParamsObservation) DeepCopy() *ParamsObservation {
	if in == nil {
		return nil
	}
	out := new(ParamsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParamsParameters) DeepCopyInto(out *ParamsParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParamsParameters.
func (in *ParamsParameters) DeepCopy() *ParamsParameters {
	if in == nil {
		return nil
	}
	out := new(ParamsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementInitParameters) DeepCopyInto(out *PlacementInitParameters) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = make([]TargetInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementInitParameters.
func (in *PlacementInitParameters) DeepCopy() *PlacementInitParameters {
	if in == nil {
		return nil
	}
	out := new(PlacementInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementObservation) DeepCopyInto(out *PlacementObservation) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = make([]TargetObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementObservation.
func (in *PlacementObservation) DeepCopy() *PlacementObservation {
	if in == nil {
		return nil
	}
	out := new(PlacementObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlacementParameters) DeepCopyInto(out *PlacementParameters) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = make([]TargetParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlacementParameters.
func (in *PlacementParameters) DeepCopy() *PlacementParameters {
	if in == nil {
		return nil
	}
	out := new(PlacementParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenamedClassesInitParameters) DeepCopyInto(out *RenamedClassesInitParameters) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenamedClassesInitParameters.
func (in *RenamedClassesInitParameters) DeepCopy() *RenamedClassesInitParameters {
	if in == nil {
		return nil
	}
	out := new(RenamedClassesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenamedClassesObservation) DeepCopyInto(out *RenamedClassesObservation) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenamedClassesObservation.
func (in *RenamedClassesObservation) DeepCopy() *RenamedClassesObservation {
	if in == nil {
		return nil
	}
	out := new(RenamedClassesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RenamedClassesParameters) DeepCopyInto(out *RenamedClassesParameters) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RenamedClassesParameters.
func (in *RenamedClassesParameters) DeepCopy() *RenamedClassesParameters {
	if in == nil {
		return nil
	}
	out := new(RenamedClassesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleInitParameters) DeepCopyInto(out *SimpleInitParameters) {
	*out = *in
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = new(float64)
		**out = **in
	}
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleInitParameters.
func (in *SimpleInitParameters) DeepCopy() *SimpleInitParameters {
	if in == nil {
		return nil
	}
	out := new(SimpleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleObservation) DeepCopyInto(out *SimpleObservation) {
	*out = *in
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = new(float64)
		**out = **in
	}
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleObservation.
func (in *SimpleObservation) DeepCopy() *SimpleObservation {
	if in == nil {
		return nil
	}
	out := new(SimpleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleParameters) DeepCopyInto(out *SimpleParameters) {
	*out = *in
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = new(float64)
		**out = **in
	}
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleParameters.
func (in *SimpleParameters) DeepCopy() *SimpleParameters {
	if in == nil {
		return nil
	}
	out := new(SimpleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepsInitParameters) DeepCopyInto(out *StepsInitParameters) {
	*out = *in
	if in.DeletedClasses != nil {
		in, out := &in.DeletedClasses, &out.DeletedClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NewClasses != nil {
		in, out := &in.NewClasses, &out.NewClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NewSqliteClasses != nil {
		in, out := &in.NewSqliteClasses, &out.NewSqliteClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RenamedClasses != nil {
		in, out := &in.RenamedClasses, &out.RenamedClasses
		*out = make([]StepsRenamedClassesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TransferredClasses != nil {
		in, out := &in.TransferredClasses, &out.TransferredClasses
		*out = make([]TransferredClassesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepsInitParameters.
func (in *StepsInitParameters) DeepCopy() *StepsInitParameters {
	if in == nil {
		return nil
	}
	out := new(StepsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepsObservation) DeepCopyInto(out *StepsObservation) {
	*out = *in
	if in.DeletedClasses != nil {
		in, out := &in.DeletedClasses, &out.DeletedClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NewClasses != nil {
		in, out := &in.NewClasses, &out.NewClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NewSqliteClasses != nil {
		in, out := &in.NewSqliteClasses, &out.NewSqliteClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RenamedClasses != nil {
		in, out := &in.RenamedClasses, &out.RenamedClasses
		*out = make([]StepsRenamedClassesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TransferredClasses != nil {
		in, out := &in.TransferredClasses, &out.TransferredClasses
		*out = make([]TransferredClassesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepsObservation.
func (in *StepsObservation) DeepCopy() *StepsObservation {
	if in == nil {
		return nil
	}
	out := new(StepsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepsParameters) DeepCopyInto(out *StepsParameters) {
	*out = *in
	if in.DeletedClasses != nil {
		in, out := &in.DeletedClasses, &out.DeletedClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NewClasses != nil {
		in, out := &in.NewClasses, &out.NewClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NewSqliteClasses != nil {
		in, out := &in.NewSqliteClasses, &out.NewSqliteClasses
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RenamedClasses != nil {
		in, out := &in.RenamedClasses, &out.RenamedClasses
		*out = make([]StepsRenamedClassesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TransferredClasses != nil {
		in, out := &in.TransferredClasses, &out.TransferredClasses
		*out = make([]TransferredClassesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepsParameters.
func (in *StepsParameters) DeepCopy() *StepsParameters {
	if in == nil {
		return nil
	}
	out := new(StepsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepsRenamedClassesInitParameters) DeepCopyInto(out *StepsRenamedClassesInitParameters) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepsRenamedClassesInitParameters.
func (in *StepsRenamedClassesInitParameters) DeepCopy() *StepsRenamedClassesInitParameters {
	if in == nil {
		return nil
	}
	out := new(StepsRenamedClassesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepsRenamedClassesObservation) DeepCopyInto(out *StepsRenamedClassesObservation) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepsRenamedClassesObservation.
func (in *StepsRenamedClassesObservation) DeepCopy() *StepsRenamedClassesObservation {
	if in == nil {
		return nil
	}
	out := new(StepsRenamedClassesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepsRenamedClassesParameters) DeepCopyInto(out *StepsRenamedClassesParameters) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepsRenamedClassesParameters.
func (in *StepsRenamedClassesParameters) DeepCopy() *StepsRenamedClassesParameters {
	if in == nil {
		return nil
	}
	out := new(StepsRenamedClassesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetInitParameters) DeepCopyInto(out *TargetInitParameters) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetInitParameters.
func (in *TargetInitParameters) DeepCopy() *TargetInitParameters {
	if in == nil {
		return nil
	}
	out := new(TargetInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetObservation) DeepCopyInto(out *TargetObservation) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetObservation.
func (in *TargetObservation) DeepCopy() *TargetObservation {
	if in == nil {
		return nil
	}
	out := new(TargetObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetParameters) DeepCopyInto(out *TargetParameters) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetParameters.
func (in *TargetParameters) DeepCopy() *TargetParameters {
	if in == nil {
		return nil
	}
	out := new(TargetParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferredClassesInitParameters) DeepCopyInto(out *TransferredClassesInitParameters) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.FromScript != nil {
		in, out := &in.FromScript, &out.FromScript
		*out = new(string)
		**out = **in
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferredClassesInitParameters.
func (in *TransferredClassesInitParameters) DeepCopy() *TransferredClassesInitParameters {
	if in == nil {
		return nil
	}
	out := new(TransferredClassesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferredClassesObservation) DeepCopyInto(out *TransferredClassesObservation) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.FromScript != nil {
		in, out := &in.FromScript, &out.FromScript
		*out = new(string)
		**out = **in
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferredClassesObservation.
func (in *TransferredClassesObservation) DeepCopy() *TransferredClassesObservation {
	if in == nil {
		return nil
	}
	out := new(TransferredClassesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransferredClassesParameters) DeepCopyInto(out *TransferredClassesParameters) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(string)
		**out = **in
	}
	if in.FromScript != nil {
		in, out := &in.FromScript, &out.FromScript
		*out = new(string)
		**out = **in
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransferredClassesParameters.
func (in *TransferredClassesParameters) DeepCopy() *TransferredClassesParameters {
	if in == nil {
		return nil
	}
	out := new(TransferredClassesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Version) DeepCopyInto(out *Version) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Version.
func (in *Version) DeepCopy() *Version {
	if in == nil {
		return nil
	}
	out := new(Version)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Version) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionInitParameters) DeepCopyInto(out *VersionInitParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = new(AnnotationsInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Assets != nil {
		in, out := &in.Assets, &out.Assets
		*out = new(AssetsInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]BindingsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompatibilityDate != nil {
		in, out := &in.CompatibilityDate, &out.CompatibilityDate
		*out = new(string)
		**out = **in
	}
	if in.CompatibilityFlags != nil {
		in, out := &in.CompatibilityFlags, &out.CompatibilityFlags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(LimitsInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.MainModule != nil {
		in, out := &in.MainModule, &out.MainModule
		*out = new(string)
		**out = **in
	}
	if in.Migrations != nil {
		in, out := &in.Migrations, &out.Migrations
		*out = new(MigrationsInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make([]ModulesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(PlacementInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.UsageModel != nil {
		in, out := &in.UsageModel, &out.UsageModel
		*out = new(string)
		**out = **in
	}
	if in.WorkerID != nil {
		in, out := &in.WorkerID, &out.WorkerID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionInitParameters.
func (in *VersionInitParameters) DeepCopy() *VersionInitParameters {
	if in == nil {
		return nil
	}
	out := new(VersionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionList) DeepCopyInto(out *VersionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Version, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionList.
func (in *VersionList) DeepCopy() *VersionList {
	if in == nil {
		return nil
	}
	out := new(VersionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VersionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionObservation) DeepCopyInto(out *VersionObservation) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = new(AnnotationsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Assets != nil {
		in, out := &in.Assets, &out.Assets
		*out = new(AssetsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]BindingsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompatibilityDate != nil {
		in, out := &in.CompatibilityDate, &out.CompatibilityDate
		*out = new(string)
		**out = **in
	}
	if in.CompatibilityFlags != nil {
		in, out := &in.CompatibilityFlags, &out.CompatibilityFlags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CreatedOn != nil {
		in, out := &in.CreatedOn, &out.CreatedOn
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(LimitsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.MainModule != nil {
		in, out := &in.MainModule, &out.MainModule
		*out = new(string)
		**out = **in
	}
	if in.MainScriptBase64 != nil {
		in, out := &in.MainScriptBase64, &out.MainScriptBase64
		*out = new(string)
		**out = **in
	}
	if in.Migrations != nil {
		in, out := &in.Migrations, &out.Migrations
		*out = new(MigrationsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make([]ModulesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Number != nil {
		in, out := &in.Number, &out.Number
		*out = new(float64)
		**out = **in
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(PlacementObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
	if in.StartupTimeMs != nil {
		in, out := &in.StartupTimeMs, &out.StartupTimeMs
		*out = new(float64)
		**out = **in
	}
	if in.UsageModel != nil {
		in, out := &in.UsageModel, &out.UsageModel
		*out = new(string)
		**out = **in
	}
	if in.WorkerID != nil {
		in, out := &in.WorkerID, &out.WorkerID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionObservation.
func (in *VersionObservation) DeepCopy() *VersionObservation {
	if in == nil {
		return nil
	}
	out := new(VersionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionParameters) DeepCopyInto(out *VersionParameters) {
	*out = *in
	if in.AccountID != nil {
		in, out := &in.AccountID, &out.AccountID
		*out = new(string)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = new(AnnotationsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Assets != nil {
		in, out := &in.Assets, &out.Assets
		*out = new(AssetsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]BindingsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CompatibilityDate != nil {
		in, out := &in.CompatibilityDate, &out.CompatibilityDate
		*out = new(string)
		**out = **in
	}
	if in.CompatibilityFlags != nil {
		in, out := &in.CompatibilityFlags, &out.CompatibilityFlags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(LimitsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.MainModule != nil {
		in, out := &in.MainModule, &out.MainModule
		*out = new(string)
		**out = **in
	}
	if in.Migrations != nil {
		in, out := &in.Migrations, &out.Migrations
		*out = new(MigrationsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make([]ModulesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(PlacementParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.UsageModel != nil {
		in, out := &in.UsageModel, &out.UsageModel
		*out = new(string)
		**out = **in
	}
	if in.WorkerID != nil {
		in, out := &in.WorkerID, &out.WorkerID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionParameters.
func (in *VersionParameters) DeepCopy() *VersionParameters {
	if in == nil {
		return nil
	}
	out := new(VersionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionSpec) DeepCopyInto(out *VersionSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionSpec.
func (in *VersionSpec) DeepCopy() *VersionSpec {
	if in == nil {
		return nil
	}
	out := new(VersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionStatus) DeepCopyInto(out *VersionStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionStatus.
func (in *VersionStatus) DeepCopy() *VersionStatus {
	if in == nil {
		return nil
	}
	out := new(VersionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerInitParameters) DeepCopyInto(out *WorkerInitParameters) {
	*out = *in
	if in.Entrypoint != nil {
		in, out := &in.Entrypoint, &out.Entrypoint
		*out = new(string)
		**out = **in
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerInitParameters.
func (in *WorkerInitParameters) DeepCopy() *WorkerInitParameters {
	if in == nil {
		return nil
	}
	out := new(WorkerInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerObservation) DeepCopyInto(out *WorkerObservation) {
	*out = *in
	if in.Entrypoint != nil {
		in, out := &in.Entrypoint, &out.Entrypoint
		*out = new(string)
		**out = **in
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerObservation.
func (in *WorkerObservation) DeepCopy() *WorkerObservation {
	if in == nil {
		return nil
	}
	out := new(WorkerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerParameters) DeepCopyInto(out *WorkerParameters) {
	*out = *in
	if in.Entrypoint != nil {
		in, out := &in.Entrypoint, &out.Entrypoint
		*out = new(string)
		**out = **in
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerParameters.
func (in *WorkerParameters) DeepCopy() *WorkerParameters {
	if in == nil {
		return nil
	}
	out := new(WorkerParameters)
	in.DeepCopyInto(out)
	return out
}
