apiVersion: zero.upjet-cloudflare.upbound.io/v1alpha1
kind: TrustAccessGroup
metadata:
  annotations:
    meta.upbound.io/example-id: zero/v1alpha1/trustaccessgroup
  labels:
    testing.upbound.io/example-name: example_zero_trust_access_group
  name: example-zero-trust-access-group
spec:
  forProvider:
    exclude:
    - certificate: {}
    include:
    - certificate: {}
    isDefault: true
    name: Allow devs
    require:
    - certificate: {}
    zoneId: zone_id
