apiVersion: organization.upjet-cloudflare.upbound.io/v1alpha1
kind: Profile
metadata:
  annotations:
    meta.upbound.io/example-id: organization/v1alpha1/profile
  labels:
    testing.upbound.io/example-name: example_organization_profile
  name: example-organization-profile
spec:
  forProvider:
    businessAddress: business_address
    businessEmail: business_email
    businessName: business_name
    businessPhone: business_phone
    externalMetadata: external_metadata
    organizationId: a7b9c3d2e8f4a1b5c6d0e9f2a3b7c4d8
