// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ScriptSubdomainInitParameters struct {

	// (String) Identifier.
	// Identifier.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (Boolean) Whether the Worker should be available on the workers.dev subdomain.
	// Whether the Worker should be available on the workers.dev subdomain.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Whether the Worker's Preview URLs should be available on the workers.dev subdomain.
	// Whether the Worker's Preview URLs should be available on the workers.dev subdomain.
	PreviewsEnabled *bool `json:"previewsEnabled,omitempty" tf:"previews_enabled,omitempty"`

	// (String) Name of the script, used in URLs and route configuration.
	// Name of the script, used in URLs and route configuration.
	ScriptName *string `json:"scriptName,omitempty" tf:"script_name,omitempty"`
}

type ScriptSubdomainObservation struct {

	// (String) Identifier.
	// Identifier.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (Boolean) Whether the Worker should be available on the workers.dev subdomain.
	// Whether the Worker should be available on the workers.dev subdomain.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Identifier for the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Whether the Worker's Preview URLs should be available on the workers.dev subdomain.
	// Whether the Worker's Preview URLs should be available on the workers.dev subdomain.
	PreviewsEnabled *bool `json:"previewsEnabled,omitempty" tf:"previews_enabled,omitempty"`

	// (String) Name of the script, used in URLs and route configuration.
	// Name of the script, used in URLs and route configuration.
	ScriptName *string `json:"scriptName,omitempty" tf:"script_name,omitempty"`
}

type ScriptSubdomainParameters struct {

	// (String) Identifier.
	// Identifier.
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (Boolean) Whether the Worker should be available on the workers.dev subdomain.
	// Whether the Worker should be available on the workers.dev subdomain.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Whether the Worker's Preview URLs should be available on the workers.dev subdomain.
	// Whether the Worker's Preview URLs should be available on the workers.dev subdomain.
	// +kubebuilder:validation:Optional
	PreviewsEnabled *bool `json:"previewsEnabled,omitempty" tf:"previews_enabled,omitempty"`

	// (String) Name of the script, used in URLs and route configuration.
	// Name of the script, used in URLs and route configuration.
	// +kubebuilder:validation:Optional
	ScriptName *string `json:"scriptName,omitempty" tf:"script_name,omitempty"`
}

// ScriptSubdomainSpec defines the desired state of ScriptSubdomain
type ScriptSubdomainSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ScriptSubdomainParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ScriptSubdomainInitParameters `json:"initProvider,omitempty"`
}

// ScriptSubdomainStatus defines the observed state of ScriptSubdomain.
type ScriptSubdomainStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ScriptSubdomainObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ScriptSubdomain is the Schema for the ScriptSubdomains API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,upjet-cloudflare}
type ScriptSubdomain struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.accountId) || (has(self.initProvider) && has(self.initProvider.accountId))",message="spec.forProvider.accountId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scriptName) || (has(self.initProvider) && has(self.initProvider.scriptName))",message="spec.forProvider.scriptName is a required parameter"
	Spec   ScriptSubdomainSpec   `json:"spec"`
	Status ScriptSubdomainStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScriptSubdomainList contains a list of ScriptSubdomains
type ScriptSubdomainList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ScriptSubdomain `json:"items"`
}

// Repository type metadata.
var (
	ScriptSubdomain_Kind             = "ScriptSubdomain"
	ScriptSubdomain_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ScriptSubdomain_Kind}.String()
	ScriptSubdomain_KindAPIVersion   = ScriptSubdomain_Kind + "." + CRDGroupVersion.String()
	ScriptSubdomain_GroupVersionKind = CRDGroupVersion.WithKind(ScriptSubdomain_Kind)
)

func init() {
	SchemeBuilder.Register(&ScriptSubdomain{}, &ScriptSubdomainList{})
}
