// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Filter) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Healthcheck) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Image) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *List) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Organization) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Queue) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Ruleset) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Snippet) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Snippets) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Stream) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *User) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Worker) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Workflow) Hub() {}
