apiVersion: cloudflare.upjet-cloudflare.m.upbound.io/v1alpha1
kind: List
metadata:
  annotations:
    meta.upbound.io/example-id: cloudflare/v1alpha1/list
  labels:
    testing.upbound.io/example-name: example_list
  name: example-list
  namespace: crossplane-system
spec:
  forProvider:
    accountId: 023e105f4ecef8ad9ca31a8372d0c353
    description: This is a note
    items:
    - ip: 1.1.1.1
    - ip: 1.1.1.2
    kind: ip
    name: list1
