apiVersion: cloudflare.upjet-cloudflare.m.upbound.io/v1alpha1
kind: Stream
metadata:
  annotations:
    meta.upbound.io/example-id: cloudflare/v1alpha1/stream
  labels:
    testing.upbound.io/example-name: example_stream
  name: example-stream
  namespace: crossplane-system
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
