apiVersion: account.upjet-cloudflare.m.upbound.io/v1alpha1
kind: Token
metadata:
  annotations:
    meta.upbound.io/example-id: account/v1alpha1/token
  labels:
    testing.upbound.io/example-name: example_account_token
  name: example-account-token
  namespace: crossplane-system
spec:
  forProvider:
    accountId: b67e14daa5f8dceeb91fe5449ba496eb
    condition:
      requestIp:
        in:
        - 123.123.123.0/24
        - 2606:4700::/32
        notIn:
        - 123.123.123.0/28
        - 2606:4700:4700::/48
    expiresOn: "2027-10-01T00:00:00Z"
    name: workers read-only token
    notBefore: "2025-10-01T00:00:00Z"
    policies:
    - effect: allow
      permissionGroups:
      - id: 1a71c399035b4950a1bd1466bbe4f420
      - id: 8b47d2786a534c08a1f94ee8f9f599ef
      resources: |-
        ${jsonencode({
              "com.cloudflare.api.account.b67e14daa5f8dceeb91fe5449ba496eb" = "*"
            })}
