// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Account) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DNSSettings) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DNSSettingsInternalView) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Member) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Subscription) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Token) Hub() {}
