// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package cluster contains Kubernetes API for the provider.
package cluster

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/access/v1alpha1"
	v1alpha1account "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/account/v1alpha1"
	v1alpha1address "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/address/v1alpha1"
	v1alpha1ai "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/ai/v1alpha1"
	v1alpha1api "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/api/v1alpha1"
	v1alpha1argo "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/argo/v1alpha1"
	v1alpha1authenticated "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/authenticated/v1alpha1"
	v1alpha1bot "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/bot/v1alpha1"
	v1alpha1byo "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/byo/v1alpha1"
	v1alpha1calls "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/calls/v1alpha1"
	v1alpha1certificate "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/certificate/v1alpha1"
	v1alpha1cloud "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/cloud/v1alpha1"
	v1alpha1cloudflare "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/cloudflare/v1alpha1"
	v1alpha1cloudforce "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/cloudforce/v1alpha1"
	v1alpha1connectivity "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/connectivity/v1alpha1"
	v1alpha1content "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/content/v1alpha1"
	v1alpha1custom "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/custom/v1alpha1"
	v1alpha1d1 "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/d1/v1alpha1"
	v1alpha1dns "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/dns/v1alpha1"
	v1alpha1email "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/email/v1alpha1"
	v1alpha1firewall "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/firewall/v1alpha1"
	v1alpha1hostname "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/hostname/v1alpha1"
	v1alpha1hyperdrive "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/hyperdrive/v1alpha1"
	v1alpha1image "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/image/v1alpha1"
	v1alpha1keyless "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/keyless/v1alpha1"
	v1alpha1leaked "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/leaked/v1alpha1"
	v1alpha1list "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/list/v1alpha1"
	v1alpha1load "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/load/v1alpha1"
	v1alpha1logpull "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/logpull/v1alpha1"
	v1alpha1logpush "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/logpush/v1alpha1"
	v1alpha1magic "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/magic/v1alpha1"
	v1alpha1managed "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/managed/v1alpha1"
	v1alpha1mtls "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/mtls/v1alpha1"
	v1alpha1notification "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/notification/v1alpha1"
	v1alpha1observatory "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/observatory/v1alpha1"
	v1alpha1organization "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/organization/v1alpha1"
	v1alpha1origin "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/origin/v1alpha1"
	v1alpha1page "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/page/v1alpha1"
	v1alpha1pages "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/pages/v1alpha1"
	v1alpha1queue "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/queue/v1alpha1"
	v1alpha1r2 "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/r2/v1alpha1"
	v1alpha1rate "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/rate/v1alpha1"
	v1alpha1regional "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/regional/v1alpha1"
	v1alpha1registrar "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/registrar/v1alpha1"
	v1alpha1schema "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/schema/v1alpha1"
	v1alpha1snippet "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/snippet/v1alpha1"
	v1alpha1spectrum "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/spectrum/v1alpha1"
	v1alpha1sso "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/sso/v1alpha1"
	v1alpha1stream "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/stream/v1alpha1"
	v1alpha1tiered "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/tiered/v1alpha1"
	v1alpha1token "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/token/v1alpha1"
	v1alpha1total "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/total/v1alpha1"
	v1alpha1turnstile "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/turnstile/v1alpha1"
	v1alpha1universal "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/universal/v1alpha1"
	v1alpha1url "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/url/v1alpha1"
	v1alpha1user "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/user/v1alpha1"
	v1alpha1cluster "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/v1alpha1"
	v1beta1 "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/v1beta1"
	v1alpha1waiting "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/waiting/v1alpha1"
	v1alpha1web "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/web/v1alpha1"
	v1alpha1web3 "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/web3/v1alpha1"
	v1alpha1worker "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/worker/v1alpha1"
	v1alpha1workers "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/workers/v1alpha1"
	v1alpha1zero "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/zero/v1alpha1"
	v1alpha1zone "github.com/wildbitca/provider-upjet-cloudflare/apis/cluster/zone/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1account.SchemeBuilder.AddToScheme,
		v1alpha1address.SchemeBuilder.AddToScheme,
		v1alpha1ai.SchemeBuilder.AddToScheme,
		v1alpha1api.SchemeBuilder.AddToScheme,
		v1alpha1argo.SchemeBuilder.AddToScheme,
		v1alpha1authenticated.SchemeBuilder.AddToScheme,
		v1alpha1bot.SchemeBuilder.AddToScheme,
		v1alpha1byo.SchemeBuilder.AddToScheme,
		v1alpha1calls.SchemeBuilder.AddToScheme,
		v1alpha1certificate.SchemeBuilder.AddToScheme,
		v1alpha1cloud.SchemeBuilder.AddToScheme,
		v1alpha1cloudflare.SchemeBuilder.AddToScheme,
		v1alpha1cloudforce.SchemeBuilder.AddToScheme,
		v1alpha1connectivity.SchemeBuilder.AddToScheme,
		v1alpha1content.SchemeBuilder.AddToScheme,
		v1alpha1custom.SchemeBuilder.AddToScheme,
		v1alpha1d1.SchemeBuilder.AddToScheme,
		v1alpha1dns.SchemeBuilder.AddToScheme,
		v1alpha1email.SchemeBuilder.AddToScheme,
		v1alpha1firewall.SchemeBuilder.AddToScheme,
		v1alpha1hostname.SchemeBuilder.AddToScheme,
		v1alpha1hyperdrive.SchemeBuilder.AddToScheme,
		v1alpha1image.SchemeBuilder.AddToScheme,
		v1alpha1keyless.SchemeBuilder.AddToScheme,
		v1alpha1leaked.SchemeBuilder.AddToScheme,
		v1alpha1list.SchemeBuilder.AddToScheme,
		v1alpha1load.SchemeBuilder.AddToScheme,
		v1alpha1logpull.SchemeBuilder.AddToScheme,
		v1alpha1logpush.SchemeBuilder.AddToScheme,
		v1alpha1magic.SchemeBuilder.AddToScheme,
		v1alpha1managed.SchemeBuilder.AddToScheme,
		v1alpha1mtls.SchemeBuilder.AddToScheme,
		v1alpha1notification.SchemeBuilder.AddToScheme,
		v1alpha1observatory.SchemeBuilder.AddToScheme,
		v1alpha1organization.SchemeBuilder.AddToScheme,
		v1alpha1origin.SchemeBuilder.AddToScheme,
		v1alpha1page.SchemeBuilder.AddToScheme,
		v1alpha1pages.SchemeBuilder.AddToScheme,
		v1alpha1queue.SchemeBuilder.AddToScheme,
		v1alpha1r2.SchemeBuilder.AddToScheme,
		v1alpha1rate.SchemeBuilder.AddToScheme,
		v1alpha1regional.SchemeBuilder.AddToScheme,
		v1alpha1registrar.SchemeBuilder.AddToScheme,
		v1alpha1schema.SchemeBuilder.AddToScheme,
		v1alpha1snippet.SchemeBuilder.AddToScheme,
		v1alpha1spectrum.SchemeBuilder.AddToScheme,
		v1alpha1sso.SchemeBuilder.AddToScheme,
		v1alpha1stream.SchemeBuilder.AddToScheme,
		v1alpha1tiered.SchemeBuilder.AddToScheme,
		v1alpha1token.SchemeBuilder.AddToScheme,
		v1alpha1total.SchemeBuilder.AddToScheme,
		v1alpha1turnstile.SchemeBuilder.AddToScheme,
		v1alpha1universal.SchemeBuilder.AddToScheme,
		v1alpha1url.SchemeBuilder.AddToScheme,
		v1alpha1user.SchemeBuilder.AddToScheme,
		v1alpha1cluster.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
		v1alpha1waiting.SchemeBuilder.AddToScheme,
		v1alpha1web.SchemeBuilder.AddToScheme,
		v1alpha1web3.SchemeBuilder.AddToScheme,
		v1alpha1worker.SchemeBuilder.AddToScheme,
		v1alpha1workers.SchemeBuilder.AddToScheme,
		v1alpha1zero.SchemeBuilder.AddToScheme,
		v1alpha1zone.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
