apiVersion: worker.upjet-cloudflare.m.upbound.io/v1alpha1
kind: Version
metadata:
  annotations:
    meta.upbound.io/example-id: worker/v1alpha1/version
  labels:
    testing.upbound.io/example-name: example_worker_version
  name: example-worker-version
  namespace: crossplane-system
spec:
  forProvider:
    accountId: 023e105f4ecef8ad9ca31a8372d0c353
    annotations:
      workersMessage: Fixed bug.
      workersTag: v1.0.1
    assets:
      config:
        basePath: /docs/
        htmlHandling: auto-trailing-slash
        notFoundHandling: 404-page
        runWorkerFirst: []
      jwtSecretRef:
        key: example-key
        name: example-secret
    bindings:
    - name: MY_ENV_VAR
      textSecretRef:
        key: example-key
        name: example-secret
      type: plain_text
    cacheOptions:
      crossVersionCache: true
      enabled: true
    compatibilityDate: "2021-01-01T00:00:00Z"
    compatibilityFlags:
    - nodejs_compat
    containers:
    - className: MyDurableObject
    exports:
      Admin:
        cache:
          enabled: true
        state: created
        type: worker
      Counter:
        container: my-container
        state: created
        storage: sqlite
        type: durable-object
      OldCounter:
        renamed_to: Counter
        state: renamed
        type: durable-object
      default:
        cache:
          enabled: false
        state: created
        type: worker
    limits:
      cpuMs: 50
      subrequests: 1000
    mainModule: index.js
    migrations:
      deletedClasses:
      - string
      newClasses:
      - string
      newSqliteClasses:
      - string
      newTag: v2
      oldTag: v1
      renamedClasses:
      - from: from
        to: to
      transferredClasses:
      - from: from
        fromScript: from_script
        to: to
    modules:
    - contentBase64: ZXhwb3J0IGRlZmF1bHQgewogIGFzeW5jIGZldGNoKHJlcXVlc3QsIGVudiwgY3R4KSB7CiAgICByZXR1cm4gbmV3IFJlc3BvbnNlKCdIZWxsbyBXb3JsZCEnKQogIH0KfQ==
      contentType: application/javascript+module
      name: index.js
    packageDependencies:
    - installedVersion: 4.17.22
      name: lodash
      packageJsonVersion: ^4.17.21
    placement:
      mode: smart
    usageModel: standard
    workerId: worker_id
