apiVersion: pages.upjet-cloudflare.m.upbound.io/v1alpha1
kind: Domain
metadata:
  annotations:
    meta.upbound.io/example-id: pages/v1alpha1/domain
  labels:
    testing.upbound.io/example-name: example_pages_domain
  name: example-pages-domain
  namespace: crossplane-system
spec:
  forProvider:
    accountId: 023e105f4ecef8ad9ca31a8372d0c353
    name: this-is-my-domain-01.com
    projectName: this-is-my-project-01
