apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-family-cloudflare
  annotations:
    meta.crossplane.io/maintainer: "Wildbit"
    meta.crossplane.io/source: "https://github.com/wildbitca/provider-upjet-cloudflare"
    meta.crossplane.io/license: "Apache-2.0"
    meta.crossplane.io/description: "Upjet-based Crossplane provider family for the Cloudflare API. Shared ProviderConfig for all Cloudflare sub-providers."
  labels:
    pkg.crossplane.io/provider-family: provider-family-cloudflare
spec:
  capabilities:
    - SafeStart
