apiVersion: zone.upjet-cloudflare.upbound.io/v1alpha1
kind: Setting
metadata:
  annotations:
    meta.upbound.io/example-id: zone/v1alpha1/setting
  labels:
    testing.upbound.io/example-name: always_online
  name: always-online
spec:
  forProvider:
    settingId: always_online
    value: "on"
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
