apiVersion: cloudflare.upjet-cloudflare.upbound.io/v1alpha1
kind: Organization
metadata:
  annotations:
    meta.upbound.io/example-id: cloudflare/v1alpha1/organization
  labels:
    testing.upbound.io/example-name: example_organization
  name: example-organization
spec:
  forProvider:
    name: name
    parent:
      id: a7b9c3d2e8f4a1b5c6d0e9f2a3b7c4d8
    profile:
      businessAddress: business_address
      businessEmail: business_email
      businessName: business_name
      businessPhone: business_phone
      externalMetadata: external_metadata
