apiVersion: cloudflare.upjet-cloudflare.upbound.io/v1alpha1
kind: Worker
metadata:
  annotations:
    meta.upbound.io/example-id: cloudflare/v1alpha1/worker
  labels:
    testing.upbound.io/example-name: example_worker
  name: example-worker
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    logpush: true
    name: my-worker
    observability:
      enabled: true
      headSamplingRate: 1
      issues:
        enabled: true
      logs:
        destinations:
        - string
        enabled: true
        headSamplingRate: 1
        invocationLogs: true
        persist: true
      redact_query_string: true
      traces:
        destinations:
        - string
        enabled: true
        headSamplingRate: 1
        persist: true
        propagationPolicy: authenticated
    previewsBaseConfig:
      cacheOptions:
        crossVersionCache: true
        enabled: true
      env:
        MY_ENV_VAR:
          type: plain_text
      limits:
        cpuMs: 50
        subrequests: 1000
      logpush: true
      observability:
        enabled: true
        headSamplingRate: 1
        issues:
          enabled: true
        logs:
          destinations:
          - string
          enabled: true
          headSamplingRate: 1
          invocationLogs: true
          persist: true
        redactQueryString: true
        traces:
          destinations:
          - string
          enabled: true
          headSamplingRate: 1
          persist: true
          propagationPolicy: authenticated
      placement:
        mode: smart
      tailConsumers:
      - name: my-tail-consumer
    subdomain:
      enabled: true
      previewsEnabled: true
    tags:
    - my-team
    - my-public-api
    tailConsumers:
    - name: my-tail-consumer
